using System.Text;
using Microsoft.CodeAnalysis;

namespace YFex.Messaging.Generator;

internal static class LiveEmitter
{
    public static void Emit(SourceProductionContext spc, LiveClassModel model)
    {
        foreach (var m in model.Methods)
        {
            if (m.NeedsMemoryPackWarning)
                spc.ReportDiagnostic(Diagnostic.Create(
                    MessagingDiagnostics.YFRPC0001,
                    Location.None,
                    m.ValueTypeFqn));

            if (m.NeedsRefreshTriggerWarning)
                spc.ReportDiagnostic(Diagnostic.Create(
                    MessagingDiagnostics.YFLIV0002,
                    Location.None,
                    m.PropertyName));
        }

        string source   = GenerateSource(model);
        string fileName = $"{model.ClassName}.Live.g.cs";
        spc.AddSource(fileName, source);
    }

    private static string GenerateSource(LiveClassModel model)
    {
        var sb = new StringBuilder(2048);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ");
            sb.Append(model.Namespace);
            sb.AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial class ");
        sb.AppendLine(model.ClassName);
        sb.AppendLine("{");

        // ── Section 1: Static descriptors + args ─────────────────────────
        AppendDescriptors(sb, model);

        // ── Section 2: ILiveState fields + suspend dirty flags + dep watcher fields ─
        sb.AppendLine();
        AppendFields(sb, model);
        AppendSuspendDirtyFields(sb, model);
        AppendDepWatcherFields(sb, model);

        // ── Section 3: Public reactive properties ─────────────────────────
        sb.AppendLine();
        AppendProperties(sb, model);

        // ── Section 4: GetPropertyChangedArgs override (MvvmStateObject) ─
        if (model.InheritsMvvmStateObject)
        {
            sb.AppendLine();
            AppendGetPropertyChangedArgsOverride(sb, model);
        }

        // ── Section 5: OnActivateCascading ────────────────────────────────
        sb.AppendLine();
        AppendOnActivateCascading(sb, model);

        // ── Section 6: OnDeactivateCascading ──────────────────────────────
        sb.AppendLine();
        AppendOnDeactivateCascading(sb, model);

        // ── Section 6b: OnSuspendCascading / OnResumeCascading ────────────
        if (model.InheritsPageViewModel)
        {
            sb.AppendLine();
            AppendOnSuspendCascading(sb, model);
            sb.AppendLine();
            AppendOnResumeCascading(sb, model);
        }

        // ── Section 7: Update callbacks ───────────────────────────────────
        sb.AppendLine();
        AppendUpdateCallbacks(sb, model);
        AppendSuspendDirtyCallbacks(sb, model);

        // ── Section 8: Dependency watcher nested classes ──────────────────
        bool anyDeps = false;
        foreach (var m in model.Methods)
            if (m.ExplicitDependencies.Count > 0) { anyDeps = true; break; }
        if (anyDeps)
        {
            sb.AppendLine();
            AppendDepWatcherClasses(sb, model);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ── Section 1: Static descriptors ────────────────────────────────────────

    private static void AppendDescriptors(StringBuilder sb, LiveClassModel model)
    {
        foreach (var m in model.Methods)
        {
            // ChangedNotification descriptor for the value property
            sb.Append("    private static readonly global::YFex.State.Notification.ChangedNotification ");
            sb.Append(DescField(m.PropertyName));
            sb.AppendLine();
            sb.Append("        = new() { PropertyName = nameof(");
            sb.Append(m.PropertyName);
            sb.Append("), PropertyId = ");
            sb.Append(m.BasePropertyId);
            sb.AppendLine("u };");

            if (model.InheritsMvvmStateObject)
            {
                // PropertyChangedEventArgs for value, IsLoading, Error, LastFetchedAt, IsStale, IsFromOfflineCache
                AppendPceaField(sb, m.PropertyName,                      m.PropertyName);
                AppendPceaField(sb, $"Is{m.PropertyName}Loading",        $"Is{m.PropertyName}Loading");
                AppendPceaField(sb, $"{m.PropertyName}Error",            $"{m.PropertyName}Error");
                AppendPceaField(sb, $"{m.PropertyName}LastFetchedAt",    $"{m.PropertyName}LastFetchedAt");
                AppendPceaField(sb, $"Is{m.PropertyName}Stale",         $"Is{m.PropertyName}Stale");
                AppendPceaField(sb, $"Is{m.PropertyName}FromOfflineCache", $"Is{m.PropertyName}FromOfflineCache");
            }
        }
    }

    private static void AppendPceaField(StringBuilder sb, string fieldSuffix, string propName)
    {
        sb.Append("    private static readonly global::System.ComponentModel.PropertyChangedEventArgs ");
        sb.Append(ArgsField(fieldSuffix));
        sb.Append(" = new(nameof(");
        sb.Append(propName);
        sb.AppendLine("));");
    }

    // ── Section 2: ILiveState fields ─────────────────────────────────────────

    private static void AppendFields(StringBuilder sb, LiveClassModel model)
    {
        foreach (var m in model.Methods)
        {
            sb.Append("    private global::YFex.Messaging.ILiveState<");
            sb.Append(m.ValueTypeFqn);
            sb.Append(">? ");
            sb.Append(LiveField(m.PropertyName));
            sb.AppendLine(";");
        }
    }

    // ── Section 3: Public reactive properties ────────────────────────────────

    private static void AppendProperties(StringBuilder sb, LiveClassModel model)
    {
        foreach (var m in model.Methods)
        {
            string field = LiveField(m.PropertyName);

            // Value property
            sb.Append("    public ");
            sb.Append(m.ValueTypeFqn);
            sb.Append("? ");
            sb.Append(m.PropertyName);
            sb.AppendLine();
            sb.Append("        => ");
            sb.Append(field);
            sb.AppendLine("?.Value;");
            sb.AppendLine();

            // IsLoading
            sb.Append("    public bool Is");
            sb.Append(m.PropertyName);
            sb.AppendLine("Loading");
            sb.Append("        => ");
            sb.Append(field);
            sb.AppendLine("?.IsLoading ?? false;");
            sb.AppendLine();

            // Error
            sb.Append("    public global::System.Exception? ");
            sb.Append(m.PropertyName);
            sb.AppendLine("Error");
            sb.Append("        => ");
            sb.Append(field);
            sb.AppendLine("?.Error;");
            sb.AppendLine();

            // LastFetchedAt
            sb.Append("    public global::System.DateTimeOffset? ");
            sb.Append(m.PropertyName);
            sb.AppendLine("LastFetchedAt");
            sb.Append("        => ");
            sb.Append(field);
            sb.AppendLine("?.LastFetchedAt;");
            sb.AppendLine();

            // IsStale
            sb.Append("    public bool Is");
            sb.Append(m.PropertyName);
            sb.AppendLine("Stale");
            sb.Append("        => ");
            sb.Append(field);
            sb.AppendLine("?.IsStale ?? false;");
            sb.AppendLine();

            // IsFromOfflineCache
            sb.Append("    public bool Is");
            sb.Append(m.PropertyName);
            sb.AppendLine("FromOfflineCache");
            sb.Append("        => ");
            sb.Append(field);
            sb.AppendLine("?.IsFromOfflineCache ?? false;");
            sb.AppendLine();

            // RefreshAsync
            sb.Append("    public global::System.Threading.Tasks.Task Refresh");
            sb.Append(m.PropertyName);
            sb.AppendLine("Async(global::System.Threading.CancellationToken ct = default)");
            sb.Append("        => ");
            sb.Append(field);
            sb.AppendLine("?.RecomputeAsync(ct) ?? global::System.Threading.Tasks.Task.CompletedTask;");
        }
    }

    // ── Section 4: GetPropertyChangedArgs override ───────────────────────────

    private static void AppendGetPropertyChangedArgsOverride(StringBuilder sb, LiveClassModel model)
    {
        sb.AppendLine("    protected override global::System.ComponentModel.PropertyChangedEventArgs?");
        sb.AppendLine("        GetPropertyChangedArgs(uint id)");
        sb.AppendLine("    {");
        sb.AppendLine("        return id switch");
        sb.AppendLine("        {");

        foreach (var m in model.Methods)
        {
            uint idValue              = m.BasePropertyId;
            uint idIsLoading          = m.BasePropertyId + 1;
            uint idError              = m.BasePropertyId + 2;
            uint idLastFetchedAt      = m.BasePropertyId + 3;
            uint idIsStale            = m.BasePropertyId + 4;
            uint idIsFromOfflineCache = m.BasePropertyId + 5;

            sb.Append("            "); sb.Append(idValue);              sb.Append("u => "); sb.Append(ArgsField(m.PropertyName));                          sb.AppendLine(",");
            sb.Append("            "); sb.Append(idIsLoading);          sb.Append("u => "); sb.Append(ArgsField($"Is{m.PropertyName}Loading"));            sb.AppendLine(",");
            sb.Append("            "); sb.Append(idError);              sb.Append("u => "); sb.Append(ArgsField($"{m.PropertyName}Error"));                sb.AppendLine(",");
            sb.Append("            "); sb.Append(idLastFetchedAt);      sb.Append("u => "); sb.Append(ArgsField($"{m.PropertyName}LastFetchedAt"));        sb.AppendLine(",");
            sb.Append("            "); sb.Append(idIsStale);            sb.Append("u => "); sb.Append(ArgsField($"Is{m.PropertyName}Stale"));              sb.AppendLine(",");
            sb.Append("            "); sb.Append(idIsFromOfflineCache); sb.Append("u => "); sb.Append(ArgsField($"Is{m.PropertyName}FromOfflineCache"));   sb.AppendLine(",");
        }

        sb.AppendLine("            _ => base.GetPropertyChangedArgs(id)");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    // ── Section 5: OnActivateCascading ───────────────────────────────────────

    private static void AppendOnActivateCascading(StringBuilder sb, LiveClassModel model)
    {
        sb.AppendLine("    protected override void OnActivateCascading()");
        sb.AppendLine("    {");
        sb.AppendLine("        base.OnActivateCascading();");

        foreach (var m in model.Methods)
        {
            string field = LiveField(m.PropertyName);

            // Build LiveStateOptions
            bool hasOpts = m.PollMs > 0 || m.Cache != 0 || m.StaleTimeMs > 0;
            string opts;
            if (!hasOpts)
            {
                opts = "default";
            }
            else
            {
                var parts = new System.Collections.Generic.List<string>();
                if (m.PollMs > 0)      parts.Add($"PollMs = {m.PollMs}");
                if (m.Cache != 0)      parts.Add($"Cache = (global::YFex.Messaging.LiveCache){m.Cache}");
                if (m.StaleTimeMs > 0) parts.Add($"StaleTimeMs = {m.StaleTimeMs}");
                opts = $"new global::YFex.Messaging.LiveStateOptions {{ {string.Join(", ", parts)} }}";
            }

            sb.Append("        ");
            sb.Append(field);
            sb.Append(" = global::YFex.Messaging.LiveStateProvider.Current.Create<");
            sb.Append(m.ValueTypeFqn);
            sb.Append(">(ct => ");
            sb.Append(m.MethodName);
            sb.Append("(ct), ");
            sb.Append(opts);
            sb.AppendLine(");");

            sb.Append("        ");
            sb.Append(field);
            sb.Append(".Updated += ");
            sb.Append(CallbackName(m.PropertyName));
            sb.AppendLine(";");

            // Wire explicit dependency watchers
            if (m.ExplicitDependencies.Count > 0)
            {
                string depField = DepWatcherFieldName(m.PropertyName);
                sb.Append("        "); sb.Append(depField);
                sb.Append(" = new "); sb.Append(DepWatcherClassName(m.PropertyName));
                sb.AppendLine("(this);");
                sb.Append("        this.Subscribe("); sb.Append(depField); sb.AppendLine(");");
            }
        }

        sb.AppendLine("    }");
    }

    // ── Section 6: OnDeactivateCascading ─────────────────────────────────────

    private static void AppendOnDeactivateCascading(StringBuilder sb, LiveClassModel model)
    {
        sb.AppendLine("    protected override void OnDeactivateCascading()");
        sb.AppendLine("    {");

        foreach (var m in model.Methods)
        {
            string field = LiveField(m.PropertyName);

            // Unsubscribe dependency watcher
            if (m.ExplicitDependencies.Count > 0)
            {
                string depField = DepWatcherFieldName(m.PropertyName);
                sb.Append("        if ("); sb.Append(depField); sb.AppendLine(" is not null)");
                sb.AppendLine("        {");
                sb.Append("            this.Unsubscribe("); sb.Append(depField); sb.AppendLine(");");
                sb.Append("            "); sb.Append(depField); sb.AppendLine(" = null;");
                sb.AppendLine("        }");
            }

            sb.Append("        if (");
            sb.Append(field);
            sb.AppendLine(" is not null)");
            sb.AppendLine("        {");

            sb.Append("            ");
            sb.Append(field);
            sb.Append(".Updated -= ");
            sb.Append(CallbackName(m.PropertyName));
            sb.AppendLine(";");

            sb.Append("            ");
            sb.Append(field);
            sb.AppendLine(".Dispose();");

            sb.Append("            ");
            sb.Append(field);
            sb.AppendLine(" = null;");

            sb.AppendLine("        }");
        }

        sb.AppendLine("        base.OnDeactivateCascading();");
        sb.AppendLine("    }");
    }

    // ── Section 7: Update callbacks ───────────────────────────────────────────

    private static void AppendUpdateCallbacks(StringBuilder sb, LiveClassModel model)
    {
        foreach (var m in model.Methods)
        {
            sb.Append("    private void ");
            sb.Append(CallbackName(m.PropertyName));
            sb.Append("(global::YFex.Messaging.ILiveState<");
            sb.Append(m.ValueTypeFqn);
            sb.AppendLine("> state)");
            sb.AppendLine("    {");

            // Fire notification for value, IsLoading, Error using their IDs
            sb.Append("        this.FireNotification(in ");
            sb.Append(DescField(m.PropertyName));
            sb.AppendLine(");");

            if (model.InheritsMvvmStateObject)
            {
                AppendInlineNotification(sb, $"Is{m.PropertyName}Loading",        m.BasePropertyId + 1);
                AppendInlineNotification(sb, $"{m.PropertyName}Error",            m.BasePropertyId + 2);
                AppendInlineNotification(sb, $"{m.PropertyName}LastFetchedAt",    m.BasePropertyId + 3);
                AppendInlineNotification(sb, $"Is{m.PropertyName}Stale",         m.BasePropertyId + 4);
                AppendInlineNotification(sb, $"Is{m.PropertyName}FromOfflineCache", m.BasePropertyId + 5);
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    // ── Section helper: dep watcher fields ───────────────────────────────────

    private static void AppendDepWatcherFields(StringBuilder sb, LiveClassModel model)
    {
        foreach (var m in model.Methods)
        {
            if (m.ExplicitDependencies.Count == 0) continue;
            sb.Append("    private ");
            sb.Append(DepWatcherClassName(m.PropertyName));
            sb.Append("? ");
            sb.Append(DepWatcherFieldName(m.PropertyName));
            sb.AppendLine(";");
        }
    }

    // ── Section helper: dep watcher nested classes ────────────────────────────

    private static void AppendDepWatcherClasses(StringBuilder sb, LiveClassModel model)
    {
        foreach (var m in model.Methods)
        {
            if (m.ExplicitDependencies.Count == 0) continue;

            string className = DepWatcherClassName(m.PropertyName);
            string liveField = LiveField(m.PropertyName);

            sb.Append("    private sealed class ");
            sb.Append(className);
            sb.AppendLine(" : global::YFex.State.Notification.IChangedHandler");
            sb.AppendLine("    {");
            sb.Append("        private readonly "); sb.Append(model.ClassName); sb.AppendLine(" _vm;");
            sb.Append("        internal "); sb.Append(className);
            sb.Append("("); sb.Append(model.ClassName); sb.AppendLine(" vm) => _vm = vm;");
            sb.AppendLine();
            sb.AppendLine("        public void OnChanged(object sender,");
            sb.AppendLine("            in global::YFex.State.Notification.ChangedNotification n)");
            sb.AppendLine("        {");

            // Emit property name check — OR-chain of all declared dependencies
            sb.Append("            if (n.PropertyName is ");
            int depCount = m.ExplicitDependencies.Count;
            for (int i = 0; i < depCount; i++)
            {
                if (i > 0) sb.Append(" or ");
                sb.Append('"'); sb.Append(m.ExplicitDependencies[i]); sb.Append('"');
            }
            sb.AppendLine(")");
            sb.Append("                _ = _vm."); sb.Append(liveField);
            sb.AppendLine("?.RecomputeAsync();");

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    // ── Section helper: suspend dirty flag fields ────────────────────────────

    private static void AppendSuspendDirtyFields(StringBuilder sb, LiveClassModel model)
    {
        if (!model.InheritsPageViewModel) return;
        foreach (var m in model.Methods)
        {
            // Dirty flag only needed for PauseAndRefreshOnResume (0)
            if (m.SuspendBehavior != 0) continue;
            sb.Append("    private bool ");
            sb.Append(SuspendDirtyField(m.PropertyName));
            sb.AppendLine(";");
        }
    }

    // ── Section 6b: OnSuspendCascading ───────────────────────────────────────

    private static void AppendOnSuspendCascading(StringBuilder sb, LiveClassModel model)
    {
        sb.AppendLine("    protected override void OnSuspendCascading()");
        sb.AppendLine("    {");
        sb.AppendLine("        base.OnSuspendCascading();");

        foreach (var m in model.Methods)
        {
            string field = LiveField(m.PropertyName);

            // StayLive: do nothing
            if (m.SuspendBehavior == 1) continue;

            // PauseAndRefreshOnResume (0), AlwaysRefetchOnResume (2), FreezeOnSuspend (3):
            // unsubscribe the main callback
            sb.Append("        if ("); sb.Append(field); sb.AppendLine(" is not null)");
            sb.AppendLine("        {");
            sb.Append("            "); sb.Append(field);
            sb.Append(".Updated -= "); sb.Append(CallbackName(m.PropertyName));
            sb.AppendLine(";");

            // PauseAndRefreshOnResume: subscribe dirty-setter + reset flag
            if (m.SuspendBehavior == 0)
            {
                sb.Append("            "); sb.Append(SuspendDirtyField(m.PropertyName));
                sb.AppendLine(" = false;");
                sb.Append("            "); sb.Append(field);
                sb.Append(".Updated += "); sb.Append(SuspendDirtyCallback(m.PropertyName));
                sb.AppendLine(";");
            }

            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
    }

    // ── Section 6b: OnResumeCascading ────────────────────────────────────────

    private static void AppendOnResumeCascading(StringBuilder sb, LiveClassModel model)
    {
        sb.AppendLine("    protected override void OnResumeCascading()");
        sb.AppendLine("    {");
        sb.AppendLine("        base.OnResumeCascading();");

        foreach (var m in model.Methods)
        {
            string field = LiveField(m.PropertyName);

            // StayLive: do nothing
            if (m.SuspendBehavior == 1) continue;

            sb.Append("        if ("); sb.Append(field); sb.AppendLine(" is not null)");
            sb.AppendLine("        {");

            // PauseAndRefreshOnResume (0): unsubscribe dirty setter, re-subscribe main, refresh if dirty
            if (m.SuspendBehavior == 0)
            {
                sb.Append("            "); sb.Append(field);
                sb.Append(".Updated -= "); sb.Append(SuspendDirtyCallback(m.PropertyName));
                sb.AppendLine(";");
                sb.Append("            "); sb.Append(field);
                sb.Append(".Updated += "); sb.Append(CallbackName(m.PropertyName));
                sb.AppendLine(";");
                sb.Append("            if ("); sb.Append(SuspendDirtyField(m.PropertyName)); sb.AppendLine(")");
                sb.AppendLine("            {");
                sb.Append("                "); sb.Append(SuspendDirtyField(m.PropertyName));
                sb.AppendLine(" = false;");
                sb.Append("                _ = "); sb.Append(field); sb.AppendLine(".RecomputeAsync();");
                sb.AppendLine("            }");
            }
            // AlwaysRefetchOnResume (2): re-subscribe main, always refresh
            else if (m.SuspendBehavior == 2)
            {
                sb.Append("            "); sb.Append(field);
                sb.Append(".Updated += "); sb.Append(CallbackName(m.PropertyName));
                sb.AppendLine(";");
                sb.Append("            _ = "); sb.Append(field); sb.AppendLine(".RecomputeAsync();");
            }
            // FreezeOnSuspend (3): re-subscribe main, no refresh
            else
            {
                sb.Append("            "); sb.Append(field);
                sb.Append(".Updated += "); sb.Append(CallbackName(m.PropertyName));
                sb.AppendLine(";");
            }

            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
    }

    // ── Section helper: suspend dirty callbacks ───────────────────────────────

    private static void AppendSuspendDirtyCallbacks(StringBuilder sb, LiveClassModel model)
    {
        if (!model.InheritsPageViewModel) return;
        foreach (var m in model.Methods)
        {
            if (m.SuspendBehavior != 0) continue; // only PauseAndRefreshOnResume needs this

            sb.Append("    private void ");
            sb.Append(SuspendDirtyCallback(m.PropertyName));
            sb.Append("(global::YFex.Messaging.ILiveState<");
            sb.Append(m.ValueTypeFqn);
            sb.AppendLine("> _)");
            sb.Append("        => "); sb.Append(SuspendDirtyField(m.PropertyName));
            sb.AppendLine(" = true;");
            sb.AppendLine();
        }
    }

    // ── Name helpers ──────────────────────────────────────────────────────────

    private static string LiveField(string propName)           => $"__live_{propName}";
    private static string DescField(string propName)           => $"__liveDesc_{propName}";
    private static string ArgsField(string propName)           => $"__liveArgs_{propName}";
    private static string CallbackName(string propName)        => $"__OnLive{propName}Updated";
    private static string SuspendDirtyField(string propName)   => $"__live_{propName}_isDirty";
    private static string SuspendDirtyCallback(string propName) => $"__OnLive{propName}Dirtied";
    private static string DepWatcherClassName(string propName)  => $"__LiveDep_{propName}";
    private static string DepWatcherFieldName(string propName)  => $"__liveDep_{propName}";

    private static void AppendInlineNotification(StringBuilder sb, string propertyName, uint propertyId)
    {
        sb.Append("        this.FireNotification(new global::YFex.State.Notification.ChangedNotification");
        sb.Append(" { PropertyName = nameof(");
        sb.Append(propertyName);
        sb.Append("), PropertyId = ");
        sb.Append(propertyId);
        sb.AppendLine("u });");
    }
}
