using System;
using System.Text;
using Microsoft.CodeAnalysis;

namespace YFex.Messaging.Generator;

internal static class MessagingEmitter
{
    public static void Emit(SourceProductionContext spc, SubscribeClassModel model)
    {
        // ── YFSUB001: class is not partial ────────────────────────────────
        if (!model.IsPartial)
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                MessagingDiagnostics.YFSUB001,
                Location.None,
                model.ClassName));
            return; // nothing to emit without partial
        }

        // ── YFSUB002: unsupported base class ──────────────────────────────
        if (!model.ValidBase)
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                MessagingDiagnostics.YFSUB002,
                Location.None,
                model.ClassName));
            return;
        }

        // ── YFRPC0001: cross-boundary methods without [MemoryPackable] ────
        foreach (var m in model.Methods)
        {
            if (m.NeedsMemoryPackWarning)
                spc.ReportDiagnostic(Diagnostic.Create(
                    MessagingDiagnostics.YFRPC0001,
                    Location.None,
                    m.EventTypeFqn));
        }

        string source   = GenerateSource(model);
        string fileName = $"{model.ClassName}.Messaging.g.cs";
        spc.AddSource(fileName, source);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Full file generation — branches on StateObject vs MessagingHost
    // ─────────────────────────────────────────────────────────────────────────

    private static string GenerateSource(SubscribeClassModel model)
    {
        var sb = new StringBuilder(1024);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ");
            sb.Append(model.Namespace);
            sb.AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial class ");
        sb.AppendLine(model.ClassName);
        sb.AppendLine("{");

        // ── Section 1: Private adapter nested classes ─────────────────────
        AppendAdapterClasses(sb, model);

        if (model.IsMessagingHost)
        {
            // ── Pipeline C: MessagingHost — OnHostStarting ────────────────
            sb.AppendLine();
            AppendOnHostStarting(sb, model);
        }
        else
        {
            // ── Pipeline B: StateObject — activate / deactivate ───────────
            // ── Section 2: Subscription fields ───────────────────────────
            sb.AppendLine();
            AppendSubscriptionFields(sb, model);

            // ── Section 3: OnActivateCascading override ───────────────────
            sb.AppendLine();
            AppendOnActivateCascading(sb, model);

            // ── Section 4: OnDeactivateCascading override ─────────────────
            sb.AppendLine();
            AppendOnDeactivateCascading(sb, model);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Section 1: Adapter classes
    // Each [Subscribe<T>] method gets its own private sealed adapter class.
    // When DebounceMs or ThrottleMs > 0 the adapter additionally implements
    // IDisposable to clean up the internal System.Threading.Timer.
    // ─────────────────────────────────────────────────────────────────────────

    private static void AppendAdapterClasses(StringBuilder sb, SubscribeClassModel model)
    {
        foreach (var method in model.Methods)
        {
            bool hasTimer = method.DebounceMs > 0 || method.ThrottleMs > 0;
            string adapterName = AdapterClassName(method.MethodName);

            // Class declaration
            sb.Append("    private sealed class ");
            sb.Append(adapterName);
            sb.AppendLine();
            sb.Append("        : global::YFex.Messaging.");
            sb.Append(RecipientInterface(method));
            if (hasTimer) sb.AppendLine(", global::System.IDisposable");
            else          sb.AppendLine();
            sb.AppendLine("    {");

            // Field: owner VM
            sb.Append("        private readonly ");
            sb.Append(model.ClassName);
            sb.AppendLine(" _vm;");

            if (hasTimer)
            {
                // Additional fields for timer-based delivery
                sb.Append("        private ");
                sb.Append(method.EventTypeFqn);
                sb.AppendLine(" _pending;");
                sb.AppendLine("        private global::System.Threading.Timer? _timer;");
                sb.AppendLine("        private readonly object _lock = new();");
            }

            sb.AppendLine();

            // Constructor
            sb.Append("        public ");
            sb.Append(adapterName);
            sb.Append('(');
            sb.Append(model.ClassName);
            sb.AppendLine(" vm) => _vm = vm;");
            sb.AppendLine();

            // Interface method implementation
            if (hasTimer)
            {
                if (method.DebounceMs > 0)
                    AppendDebounceInterfaceImpl(sb, method);
                else
                    AppendThrottleInterfaceImpl(sb, method);

                AppendTimerFlush(sb, method);
                AppendTimerDispose(sb);
            }
            else
            {
                if (method.IsAsync)
                    AppendAsyncInterfaceImpl(sb, method);
                else
                    AppendSyncInterfaceImpl(sb, method);
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    // ── Debounce: reset timer on each event; fire after silence period ────────

    private static void AppendDebounceInterfaceImpl(StringBuilder sb, SubscribeMethodModel method)
    {
        AppendReceiveSignature(sb, method);
        sb.AppendLine("        {");
        AppendMatchGuards(sb, method);
        sb.AppendLine("            lock (_lock)");
        sb.AppendLine("            {");
        sb.AppendLine("                _pending = e;");
        sb.AppendLine("                if (_timer is null)");
        sb.Append("                    _timer = new global::System.Threading.Timer(");
        sb.Append("Flush, null, "); sb.Append(method.DebounceMs);
        sb.AppendLine(", global::System.Threading.Timeout.Infinite);");
        sb.AppendLine("                else");
        sb.Append("                    _timer.Change("); sb.Append(method.DebounceMs);
        sb.AppendLine(", global::System.Threading.Timeout.Infinite);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    // ── Throttle: fire immediately, suppress events for window period ─────────

    private static void AppendThrottleInterfaceImpl(StringBuilder sb, SubscribeMethodModel method)
    {
        AppendReceiveSignature(sb, method);
        sb.AppendLine("        {");
        AppendMatchGuards(sb, method);
        sb.AppendLine("            lock (_lock)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (_timer is not null) return; // throttled");
        sb.Append("                _timer = new global::System.Threading.Timer(_ => { lock (_lock) { _timer = null; } }, null, ");
        sb.Append(method.ThrottleMs); sb.AppendLine(", global::System.Threading.Timeout.Infinite);");
        sb.AppendLine("            }");
        // Fire outside lock — at this point we have the event in `e`
        AppendFlushCall(sb, method, eventExpr: "e");
        sb.AppendLine("        }");
    }

    // ── Shared: emit the Receive/ReceiveAsync signature ───────────────────────

    private static void AppendReceiveSignature(StringBuilder sb, SubscribeMethodModel method)
    {
        if (method.IsAsync)
        {
            sb.AppendLine("        global::System.Threading.Tasks.ValueTask");
            sb.Append("            global::YFex.Messaging.IAsyncEventRecipient<");
            sb.Append(method.EventTypeFqn);
            sb.Append(">.ReceiveAsync(");
            sb.Append(method.EventTypeFqn);
            sb.AppendLine(" e, global::System.Threading.CancellationToken ct)");
        }
        else
        {
            sb.AppendLine("        void");
            sb.Append("            global::YFex.Messaging.IEventRecipient<");
            sb.Append(method.EventTypeFqn);
            sb.Append(">.Receive(in ");
            sb.Append(method.EventTypeFqn);
            sb.AppendLine(" e)");
        }
    }

    // ── Timer flush: copy pending and call the VM handler ─────────────────────

    private static void AppendTimerFlush(StringBuilder sb, SubscribeMethodModel method)
    {
        sb.AppendLine();
        sb.AppendLine("        private void Flush(object? _)");
        sb.AppendLine("        {");
        sb.Append("            "); sb.Append(method.EventTypeFqn);
        sb.AppendLine(" e;");
        sb.AppendLine("            lock (_lock) { e = _pending; _timer = null; }");
        AppendFlushCall(sb, method, eventExpr: "e");
        sb.AppendLine("        }");
    }

    private static void AppendFlushCall(StringBuilder sb, SubscribeMethodModel method, string eventExpr)
    {
        if (method.IsAsync)
        {
            sb.Append("            _ = _vm."); sb.Append(method.MethodName);
            sb.Append("("); sb.Append(eventExpr);
            sb.AppendLine(", global::System.Threading.CancellationToken.None).AsTask();");
        }
        else
        {
            sb.Append("            _vm."); sb.Append(method.MethodName);
            sb.Append("(in "); sb.Append(eventExpr); sb.AppendLine(");");
        }
    }

    private static void AppendTimerDispose(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine("        public void Dispose()");
        sb.AppendLine("        {");
        sb.AppendLine("            lock (_lock) { _timer?.Dispose(); _timer = null; }");
        sb.AppendLine("        }");
    }

    private static void AppendAsyncInterfaceImpl(StringBuilder sb, SubscribeMethodModel method)
    {
        sb.AppendLine("        async global::System.Threading.Tasks.ValueTask");
        sb.Append("            global::YFex.Messaging.IAsyncEventRecipient<");
        sb.Append(method.EventTypeFqn);
        sb.AppendLine(">.ReceiveAsync(");
        sb.Append("                ");
        sb.Append(method.EventTypeFqn);
        sb.AppendLine(" e,");
        sb.AppendLine("                global::System.Threading.CancellationToken ct)");
        sb.AppendLine("        {");

        AppendMatchGuards(sb, method);

        sb.Append("            await _vm.");
        sb.Append(method.MethodName);
        sb.AppendLine("(e, ct).ConfigureAwait(false);");
        sb.AppendLine("        }");
    }

    private static void AppendSyncInterfaceImpl(StringBuilder sb, SubscribeMethodModel method)
    {
        sb.AppendLine("        void");
        sb.Append("            global::YFex.Messaging.IEventRecipient<");
        sb.Append(method.EventTypeFqn);
        sb.AppendLine(">.Receive(");
        sb.Append("                in ");
        sb.Append(method.EventTypeFqn);
        sb.AppendLine(" e)");
        sb.AppendLine("        {");

        AppendMatchGuards(sb, method);

        sb.Append("            _vm.");
        sb.Append(method.MethodName);
        sb.AppendLine("(in e);");
        sb.AppendLine("        }");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Match guards
    // "Model.Id"             → if (!object.Equals(e.Id, _vm.Model.Id)) return;
    // "Model.OrderId,X.LineId" → one guard per path
    // ─────────────────────────────────────────────────────────────────────────

    private static void AppendMatchGuards(StringBuilder sb, SubscribeMethodModel method)
    {
        if (string.IsNullOrEmpty(method.FilterBy)) return;

        string[] paths = method.FilterBy!.Split(',');
        foreach (var rawPath in paths)
        {
            string path = rawPath.Trim();
            if (string.IsNullOrEmpty(path)) continue;

            // Last segment = event property name; full path = VM access path
            int lastDot = path.LastIndexOf('.');
            string eventProp = lastDot >= 0 ? path.Substring(lastDot + 1) : path;
            string vmPath    = path;

            sb.Append("            if (!global::System.Object.Equals(e.");
            sb.Append(eventProp);
            sb.Append(", _vm.");
            sb.Append(vmPath);
            sb.AppendLine(")) return;");
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Pipeline C: MessagingHost — OnHostStarting
    //
    // For MessagingHost-derived classes, subscriptions are registered via
    // RegisterSubscription() in OnHostStarting() (called from the ctor).
    // The bus always gets KeepAlive = true so the adapter survives without a field.
    // Timer adapters (debounce/throttle) are also registered so DisposeAsync cleans them up.
    // ─────────────────────────────────────────────────────────────────────────

    private static void AppendOnHostStarting(StringBuilder sb, SubscribeClassModel model)
    {
        sb.AppendLine("    protected override void OnHostStarting()");
        sb.AppendLine("    {");
        sb.AppendLine("        base.OnHostStarting();");

        foreach (var method in model.Methods)
        {
            string adapterVar = $"__hostAdapter_{method.MethodName}";

            // Create adapter
            sb.Append("        var ");
            sb.Append(adapterVar);
            sb.Append(" = new ");
            sb.Append(AdapterClassName(method.MethodName));
            sb.AppendLine("(this);");

            // Build SubscribeOptions — always KeepAlive for MessagingHost singletons
            string optionsExpr = BuildMessagingHostOptions(method);

            // Register subscription token
            sb.Append("        RegisterSubscription(global::YFex.Messaging.EventBusProvider.Current.");
            if (method.IsAsync)
            {
                sb.Append("SubscribeAsync<");
                sb.Append(method.EventTypeFqn);
                sb.Append(">(");
            }
            else
            {
                sb.Append("Subscribe<");
                sb.Append(method.EventTypeFqn);
                sb.Append(">(");
            }
            sb.Append(adapterVar);
            sb.Append(", ");
            sb.Append(optionsExpr);
            sb.AppendLine("));");

            // Register the adapter itself if it is IDisposable (debounce/throttle timer cleanup)
            if (method.DebounceMs > 0 || method.ThrottleMs > 0)
            {
                sb.Append("        RegisterSubscription(");
                sb.Append(adapterVar);
                sb.AppendLine(");");
            }
        }

        sb.AppendLine("    }");
    }

    private static string BuildMessagingHostOptions(SubscribeMethodModel method)
    {
        // MessagingHost subscriptions are always KeepAlive so the adapter stays rooted via the bus.
        var parts = new System.Collections.Generic.List<string> { "KeepAlive = true" };

        if (method.Target is { } target)
            parts.Add($"TargetId = this.{target}");

        if (method.Group is { } group)
            parts.Add($"GroupId = this.{group}");

        return $"new global::YFex.Messaging.SubscribeOptions {{ {string.Join(", ", parts)} }}";
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Section 2: Subscription fields (adapter + token)
    // ─────────────────────────────────────────────────────────────────────────

    private static void AppendSubscriptionFields(StringBuilder sb, SubscribeClassModel model)
    {
        foreach (var method in model.Methods)
        {
            // Adapter field — keeps adapter alive (weak subscription safe)
            sb.Append("    private ");
            sb.Append(AdapterClassName(method.MethodName));
            sb.Append("? ");
            sb.Append(AdapterFieldName(method.MethodName));
            sb.AppendLine(";");

            // IDisposable subscription token
            sb.Append("    private global::System.IDisposable? ");
            sb.Append(SubFieldName(method.MethodName));
            sb.AppendLine(";");
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Section 3: OnActivateCascading — subscribe all
    // ─────────────────────────────────────────────────────────────────────────

    private static void AppendOnActivateCascading(StringBuilder sb, SubscribeClassModel model)
    {
        sb.AppendLine("    protected override void OnActivateCascading()");
        sb.AppendLine("    {");
        sb.AppendLine("        base.OnActivateCascading();");

        foreach (var method in model.Methods)
        {
            // Create adapter
            sb.Append("        ");
            sb.Append(AdapterFieldName(method.MethodName));
            sb.Append(" = new ");
            sb.Append(AdapterClassName(method.MethodName));
            sb.AppendLine("(this);");

            // Build SubscribeOptions
            string optionsExpr = BuildSubscribeOptions(method);

            // Subscribe call
            sb.Append("        ");
            sb.Append(SubFieldName(method.MethodName));
            sb.Append(" = global::YFex.Messaging.EventBusProvider.Current.");

            if (method.IsAsync)
            {
                sb.Append("SubscribeAsync<");
                sb.Append(method.EventTypeFqn);
                sb.Append(">(");
            }
            else
            {
                sb.Append("Subscribe<");
                sb.Append(method.EventTypeFqn);
                sb.Append(">(");
            }

            sb.Append(AdapterFieldName(method.MethodName));
            sb.Append(", ");
            sb.Append(optionsExpr);
            sb.AppendLine(");");
        }

        sb.AppendLine("    }");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Section 4: OnDeactivateCascading — unsubscribe all
    // ─────────────────────────────────────────────────────────────────────────

    private static void AppendOnDeactivateCascading(StringBuilder sb, SubscribeClassModel model)
    {
        sb.AppendLine("    protected override void OnDeactivateCascading()");
        sb.AppendLine("    {");

        foreach (var method in model.Methods)
        {
            sb.Append("        ");
            sb.Append(SubFieldName(method.MethodName));
            sb.AppendLine("?.Dispose();");

            sb.Append("        ");
            sb.Append(SubFieldName(method.MethodName));
            sb.AppendLine(" = null;");

            // Dispose adapter timer if present (debounce/throttle)
            if (method.DebounceMs > 0 || method.ThrottleMs > 0)
            {
                sb.Append("        ");
                sb.Append(AdapterFieldName(method.MethodName));
                sb.AppendLine("?.Dispose();");
            }

            sb.Append("        ");
            sb.Append(AdapterFieldName(method.MethodName));
            sb.AppendLine(" = null;");
        }

        sb.AppendLine("        base.OnDeactivateCascading();");
        sb.AppendLine("    }");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Helpers
    // ─────────────────────────────────────────────────────────────────────────

    private static string RecipientInterface(SubscribeMethodModel method) =>
        method.IsAsync
            ? $"IAsyncEventRecipient<{method.EventTypeFqn}>"
            : $"IEventRecipient<{method.EventTypeFqn}>";

    private static string AdapterClassName(string methodName) =>
        $"__MsgAdapter_{methodName}";

    private static string AdapterFieldName(string methodName) =>
        $"__msgAdapter_{methodName}";

    private static string SubFieldName(string methodName) =>
        $"__sub_{methodName}";

    private static string BuildSubscribeOptions(SubscribeMethodModel method)
    {
        bool hasOptions =
            method.KeepAlive          ||
            method.Target is not null ||
            method.Group  is not null;

        if (!hasOptions) return "default";

        var sb = new StringBuilder("new global::YFex.Messaging.SubscribeOptions { ");

        bool first = true;

        if (method.KeepAlive)
        {
            sb.Append("KeepAlive = true");
            first = false;
        }

        if (method.Target is { } target)
        {
            if (!first) sb.Append(", ");
            sb.Append("TargetId = this.");
            sb.Append(target);
            first = false;
        }

        if (method.Group is { } group)
        {
            if (!first) sb.Append(", ");
            sb.Append("GroupId = this.");
            sb.Append(group);
            _ = first; // consumed
        }

        sb.Append(" }");
        return sb.ToString();
    }
}
