namespace YFex.Messaging.Rpc;

/// <summary>
/// Typed client cache used for offline query serving and optimistic updates.
/// Keys are generated by the dispatcher using the format <c>query:{TypeName}:{ParameterHash}</c>.
/// </summary>
public interface IClientCache
{
    ValueTask<T?> GetAsync<T>(string key, CancellationToken ct = default);
    ValueTask SetAsync<T>(string key, T value, TimeSpan? ttl = null, CancellationToken ct = default);
    ValueTask InvalidateAsync(string key, CancellationToken ct = default);
    /// <summary>Atomically reads the current value, applies <paramref name="mutator"/>, and writes the result (for optimistic updates).</summary>
    ValueTask UpdateAsync<T>(string key, Func<T, T> mutator, CancellationToken ct = default);
    /// <summary>Marks an entry as stale without removing it — serves the value offline but triggers refresh on reconnect.</summary>
    ValueTask MarkStaleAsync(string key, CancellationToken ct = default);
    /// <summary>Returns all cache keys that begin with <paramref name="prefix"/>. Used for batch invalidation.</summary>
    ValueTask<IReadOnlyList<string>> GetKeysWithPrefixAsync(string prefix, CancellationToken ct = default);
}

/// <summary>
/// In-memory <see cref="IClientCache"/> that stores typed objects directly (no serialization).
/// </summary>
public sealed class InMemoryClientCache : IClientCache
{
    private sealed record CacheEntry(object? Value, bool IsStale, DateTimeOffset? ExpiresAt);

    private readonly Dictionary<string, CacheEntry> _cache = new(StringComparer.Ordinal);
    private readonly object _lock = new();

    public ValueTask<T?> GetAsync<T>(string key, CancellationToken ct = default)
    {
        lock (_lock)
        {
            if (!_cache.TryGetValue(key, out var e)) return new(default(T?));
            if (e.ExpiresAt.HasValue && e.ExpiresAt.Value < DateTimeOffset.UtcNow)
            {
                _cache.Remove(key);
                return new(default(T?));
            }
            return new(e.Value is T t ? t : default(T?));
        }
    }

    public ValueTask SetAsync<T>(string key, T value, TimeSpan? ttl = null, CancellationToken ct = default)
    {
        var expiresAt = ttl.HasValue ? DateTimeOffset.UtcNow + ttl.Value : (DateTimeOffset?)null;
        lock (_lock) _cache[key] = new(value, false, expiresAt);
        return ValueTask.CompletedTask;
    }

    public ValueTask InvalidateAsync(string key, CancellationToken ct = default)
    {
        lock (_lock) _cache.Remove(key);
        return ValueTask.CompletedTask;
    }

    public ValueTask UpdateAsync<T>(string key, Func<T, T> mutator, CancellationToken ct = default)
    {
        lock (_lock)
        {
            if (_cache.TryGetValue(key, out var e) && e.Value is T current)
                _cache[key] = e with { Value = mutator(current) };
        }
        return ValueTask.CompletedTask;
    }

    public ValueTask MarkStaleAsync(string key, CancellationToken ct = default)
    {
        lock (_lock)
        {
            if (_cache.TryGetValue(key, out var e))
                _cache[key] = e with { IsStale = true };
        }
        return ValueTask.CompletedTask;
    }

    /// <summary>Returns true if the entry exists and has been marked stale via <see cref="MarkStaleAsync"/>.</summary>
    public ValueTask<IReadOnlyList<string>> GetKeysWithPrefixAsync(string prefix, CancellationToken ct = default)
    {
        lock (_lock)
        {
            List<string>? keys = null;
            foreach (var k in _cache.Keys)
                if (k.StartsWith(prefix, StringComparison.Ordinal))
                    (keys ??= []).Add(k);
            return new(keys ?? (IReadOnlyList<string>)[]);
        }
    }

    public bool IsStale(string key)
    {
        lock (_lock) return _cache.TryGetValue(key, out var e) && e.IsStale;
    }
}
