using System;
using System.Text;

namespace YFex.Cqrs.SourceGenerator;

/// <summary>
/// Helpers for building generated source code strings.
/// All methods are static for better caching in the incremental pipeline.
/// </summary>
internal static class CodeBuilder
{
    // -------------------------------------------------------------------------
    // Name transformation helpers
    // -------------------------------------------------------------------------

    /// <summary>
    /// Removes a specific suffix from a name if it ends with it.
    /// "GetUserByIdQuery" -> "GetUserById"
    /// </summary>
    public static string RemoveSuffix(string name, string suffix)
    {
        if (name.EndsWith(suffix, StringComparison.Ordinal) && name.Length > suffix.Length)
            return name.Substring(0, name.Length - suffix.Length);
        return name;
    }

    /// <summary>
    /// Converts PascalCase to camelCase.
    /// "MinAge" -> "minAge", "Id" -> "id"
    /// </summary>
    public static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        if (char.IsLower(name[0])) return name;

        // Handle leading uppercase sequences like "ID" -> "id", "IDToken" -> "idToken"
        int upperCount = 0;
        while (upperCount < name.Length && char.IsUpper(name[upperCount]))
            upperCount++;

        if (upperCount == 0) return name;
        if (upperCount == 1) return char.ToLowerInvariant(name[0]) + name.Substring(1);

        // Multiple leading caps: lower all but last if followed by lowercase
        // e.g. "HTMLParser" -> "htmlParser", "URL" -> "url"
        if (upperCount == name.Length)
            return name.ToLowerInvariant();

        // "HTMLParser" -> lower first (upperCount-1) chars, keep the last uppercase
        return name.Substring(0, upperCount - 1).ToLowerInvariant()
               + name.Substring(upperCount - 1);
    }

    /// <summary>
    /// Derives the generated method name for a query record.
    /// "GetUserByIdQuery" -> "GetUserById"
    /// </summary>
    public static string GetQueryMethodName(string recordName)
        => RemoveSuffix(recordName, "Query");

    /// <summary>
    /// Derives the generated method name for a command record.
    /// "CreateUserCommand" -> "CreateUser"
    /// </summary>
    public static string GetCommandMethodName(string recordName)
        => RemoveSuffix(recordName, "Command");

    /// <summary>
    /// Derives the generated method name for an event record.
    /// "UserCreatedEvent" -> "OnUserCreated"
    /// </summary>
    public static string GetEventMethodName(string recordName)
    {
        string withoutSuffix = RemoveSuffix(recordName, "Event");
        return "On" + withoutSuffix;
    }

    // -------------------------------------------------------------------------
    // Parameter list helpers
    // -------------------------------------------------------------------------

    /// <summary>
    /// Builds a method parameter list: "int id, string name, string email"
    /// </summary>
    public static string BuildParameterList(EquatableArray<ParameterInfo> parameters)
    {
        if (parameters.IsEmpty) return string.Empty;

        var sb = new StringBuilder();
        bool first = true;
        foreach (var p in parameters)
        {
            if (!first) sb.Append(", ");
            sb.Append(p.Type);
            sb.Append(' ');
            sb.Append(p.NameCamelCase);
            first = false;
        }
        return sb.ToString();
    }

    /// <summary>
    /// Builds a record constructor argument list: "id, name, email"
    /// </summary>
    public static string BuildArgumentList(EquatableArray<ParameterInfo> parameters)
    {
        if (parameters.IsEmpty) return string.Empty;

        var sb = new StringBuilder();
        bool first = true;
        foreach (var p in parameters)
        {
            if (!first) sb.Append(", ");
            sb.Append(p.NameCamelCase);
            first = false;
        }
        return sb.ToString();
    }

    // -------------------------------------------------------------------------
    // Full file generation
    // -------------------------------------------------------------------------

    /// <summary>
    /// Generates the complete .g.cs file content for a ClassToGenerate model.
    /// </summary>
    public static string GenerateSource(ClassToGenerate model)
    {
        var sb = new StringBuilder(512);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ");
            sb.Append(model.Namespace);
            sb.AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("public partial class ");
        sb.AppendLine(model.ClassName);
        sb.AppendLine("{");

        bool first = true;

        // Query static class
        if (!model.Queries.IsEmpty)
        {
            if (!first) sb.AppendLine();
            first = false;
            AppendQueryClass(sb, model.Queries);
        }

        // Command static class
        if (!model.Commands.IsEmpty)
        {
            if (!first) sb.AppendLine();
            first = false;
            AppendCommandClass(sb, model.Commands);
        }

        // Events static class
        if (!model.Events.IsEmpty)
        {
            if (!first) sb.AppendLine();
            AppendEventsClass(sb, model.Events);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendQueryClass(StringBuilder sb, EquatableArray<QueryToGenerate> queries)
    {
        sb.AppendLine("    public partial class Queries");
        sb.AppendLine("    {");

        bool first = true;
        foreach (var query in queries)
        {
            if (!first) sb.AppendLine();
            first = false;

            string paramList = BuildParameterList(query.Parameters);
            string argList = BuildArgumentList(query.Parameters);

            sb.Append("        public static System.Threading.Tasks.Task<YFex.Cqrs.Result<");
            sb.Append(query.ReturnType);
            sb.Append(">> ");
            sb.Append(query.MethodName);
            sb.Append('(');
            sb.Append(paramList);
            sb.AppendLine(")");
            sb.AppendLine("        {");
            sb.Append("            return YFex.Cqrs.Query.Execute(new ");
            sb.Append(query.RecordName);
            sb.Append('(');
            sb.Append(argList);
            sb.AppendLine("));");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
    }

    private static void AppendCommandClass(StringBuilder sb, EquatableArray<CommandToGenerate> commands)
    {
        sb.AppendLine("    public partial class Commands");
        sb.AppendLine("    {");

        bool first = true;
        foreach (var cmd in commands)
        {
            if (!first) sb.AppendLine();
            first = false;

            string paramList = BuildParameterList(cmd.Parameters);
            string argList = BuildArgumentList(cmd.Parameters);

            sb.Append("        public static System.Threading.Tasks.Task<YFex.Cqrs.Result> ");
            sb.Append(cmd.MethodName);
            sb.Append('(');
            sb.Append(paramList);
            sb.AppendLine(")");
            sb.AppendLine("        {");
            sb.Append("            return YFex.Cqrs.Command.Execute(new ");
            sb.Append(cmd.RecordName);
            sb.Append('(');
            sb.Append(argList);
            sb.AppendLine("));");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
    }

    private static void AppendEventsClass(StringBuilder sb, EquatableArray<EventToGenerate> events)
    {
        sb.AppendLine("    public partial class Events");
        sb.AppendLine("    {");

        bool first = true;
        foreach (var evt in events)
        {
            if (!first) sb.AppendLine();
            first = false;

            // Publish helper — dispatches via the Event static facade
            sb.Append("        public static System.Threading.Tasks.Task Publish(");
            sb.Append(evt.RecordName);
            sb.AppendLine(" @event)");
            sb.AppendLine("            => YFex.Cqrs.Event.PublishAsync(@event);");
            sb.AppendLine();

            // Subscribe helper — returns IDisposable token; dispose to unsubscribe
            sb.Append("        public static System.IDisposable ");
            sb.Append(evt.MethodName);
            sb.Append("(YFex.Messaging.IEventRecipient<");
            sb.Append(evt.RecordName);
            sb.AppendLine("> recipient)");
            sb.AppendLine("            => YFex.Cqrs.Event.Subscribe(recipient);");
        }

        sb.AppendLine("    }");
    }
}
