using System;
using System.Collections.Immutable;
using System.Text;

namespace YFex.Cqrs.SourceGenerator;

internal static class CodeBuilder
{
    // ── Name helpers ──────────────────────────────────────────────────────────

    public static string RemoveSuffix(string name, string suffix)
        => name.EndsWith(suffix, StringComparison.Ordinal) && name.Length > suffix.Length
            ? name.Substring(0, name.Length - suffix.Length)
            : name;

    public static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        if (char.IsLower(name[0])) return name;

        int upper = 0;
        while (upper < name.Length && char.IsUpper(name[upper])) upper++;

        if (upper == 0) return name;
        if (upper == 1) return char.ToLowerInvariant(name[0]) + name.Substring(1);
        if (upper == name.Length) return name.ToLowerInvariant();
        return name.Substring(0, upper - 1).ToLowerInvariant() + name.Substring(upper - 1);
    }

    public static string GetQueryMethodName(string recordName)   => RemoveSuffix(recordName, "Query");
    public static string GetCommandMethodName(string recordName) => RemoveSuffix(recordName, "Command");
    public static string GetEventMethodName(string recordName)   => RemoveSuffix(recordName, "Event");

    // ── Parameter lists ───────────────────────────────────────────────────────

    public static string BuildParameterList(EquatableArray<ParameterInfo> parameters)
    {
        if (parameters.IsEmpty) return string.Empty;
        var sb = new StringBuilder();
        bool first = true;
        foreach (var p in parameters)
        {
            if (!first) sb.Append(", ");
            sb.Append(p.Type);
            sb.Append(' ');
            sb.Append(p.NameCamelCase);
            first = false;
        }
        return sb.ToString();
    }

    public static string BuildArgumentList(EquatableArray<ParameterInfo> parameters)
    {
        if (parameters.IsEmpty) return string.Empty;
        var sb = new StringBuilder();
        bool first = true;
        foreach (var p in parameters)
        {
            if (!first) sb.Append(", ");
            sb.Append(p.NameCamelCase);
            first = false;
        }
        return sb.ToString();
    }

    // ── Pipeline A: Static helpers ────────────────────────────────────────────

    public static string GenerateSource(ClassToGenerate model)
    {
        var sb = new StringBuilder(512);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("public partial class ").AppendLine(model.ClassName);
        sb.AppendLine("{");

        bool first = true;

        if (!model.Queries.IsEmpty)
        {
            first = false;
            AppendQueryClass(sb, model.Queries);
        }

        if (!model.Commands.IsEmpty)
        {
            if (!first) sb.AppendLine();
            first = false;
            AppendCommandClass(sb, model.Commands);
        }

        if (!model.Events.IsEmpty)
        {
            if (!first) sb.AppendLine();
            AppendEventsClass(sb, model.Events);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendQueryClass(StringBuilder sb, EquatableArray<QueryToGenerate> queries)
    {
        sb.AppendLine("    public static partial class Queries");
        sb.AppendLine("    {");

        bool first = true;
        foreach (var q in queries)
        {
            if (!first) sb.AppendLine();
            first = false;

            string paramList = BuildParameterList(q.Parameters);
            string argList   = BuildArgumentList(q.Parameters);

            // ValueTask<Result<TResult>> MethodName(params..., CancellationToken ct = default)
            sb.Append("        public static System.Threading.Tasks.ValueTask<YFex.Cqrs.Result<");
            sb.Append(q.ReturnType);
            sb.Append(">> ");
            sb.Append(q.MethodName);
            sb.Append('(');
            if (!string.IsNullOrEmpty(paramList)) { sb.Append(paramList); sb.Append(", "); }
            sb.AppendLine("System.Threading.CancellationToken ct = default)");
            sb.AppendLine("        {");
            sb.Append("            var q = new ");
            sb.Append(q.RecordName);
            sb.Append('(');
            sb.Append(argList);
            sb.AppendLine(");");
            sb.Append("            return YFex.Cqrs.YFexDispatcherProvider.Current.QueryAsync<");
            sb.Append(q.RecordName);
            sb.Append(", ");
            sb.Append(q.ReturnType);
            sb.AppendLine(">(q, ct);");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
    }

    private static void AppendCommandClass(StringBuilder sb, EquatableArray<CommandToGenerate> commands)
    {
        sb.AppendLine("    public static partial class Commands");
        sb.AppendLine("    {");

        bool first = true;
        foreach (var cmd in commands)
        {
            if (!first) sb.AppendLine();
            first = false;

            string paramList = BuildParameterList(cmd.Parameters);
            string argList   = BuildArgumentList(cmd.Parameters);

            bool hasResult    = !string.IsNullOrEmpty(cmd.ResultType);
            bool isQueueable  = cmd.IsQueueable;

            if (hasResult)
            {
                // ICommand<TResult>: QueueableResult<TResult> if IQueueable, else Result<TResult>
                string returnType = isQueueable
                    ? $"System.Threading.Tasks.ValueTask<YFex.Cqrs.QueueableResult<{cmd.ResultType}>>"
                    : $"System.Threading.Tasks.ValueTask<YFex.Cqrs.Result<{cmd.ResultType}>>";

                sb.Append("        public static ").Append(returnType).Append(' ');
                sb.Append(cmd.MethodName);
                sb.Append('(');
                if (!string.IsNullOrEmpty(paramList)) { sb.Append(paramList); sb.Append(", "); }
                sb.AppendLine("System.Threading.CancellationToken ct = default)");
                sb.AppendLine("        {");
                sb.Append("            var cmd = new ").Append(cmd.RecordName).Append('(').Append(argList).AppendLine(");");

                if (isQueueable)
                {
                    sb.Append("            return YFex.Cqrs.YFexDispatcherProvider.Current.CommandAsync<");
                    sb.Append(cmd.RecordName).Append(", ").Append(cmd.ResultType).AppendLine(">(cmd, ct);");
                }
                else
                {
                    // Non-queueable: unwrap QueueableResult<T> → Result<T>
                    sb.Append("            return UnwrapAsync_").Append(cmd.MethodName).AppendLine("(cmd, ct);");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    // Emit the private unwrap helper
                    sb.Append("        private static async System.Threading.Tasks.ValueTask<YFex.Cqrs.Result<");
                    sb.Append(cmd.ResultType).Append(">> UnwrapAsync_").Append(cmd.MethodName);
                    sb.Append('(').Append(cmd.RecordName).AppendLine(" cmd, System.Threading.CancellationToken ct)");
                    sb.AppendLine("        {");
                    sb.Append("            var r = await YFex.Cqrs.YFexDispatcherProvider.Current.CommandAsync<");
                    sb.Append(cmd.RecordName).Append(", ").Append(cmd.ResultType).AppendLine(">(cmd, ct).ConfigureAwait(false);");
                    sb.AppendLine("            return r.ToResult();");
                    // Don't close twice — continue below
                }
            }
            else
            {
                // ICommand (no result): QueueableResult if IQueueable, else Result
                string returnType = isQueueable
                    ? "System.Threading.Tasks.ValueTask<YFex.Cqrs.QueueableResult>"
                    : "System.Threading.Tasks.ValueTask<YFex.Cqrs.Result>";

                sb.Append("        public static ").Append(returnType).Append(' ');
                sb.Append(cmd.MethodName);
                sb.Append('(');
                if (!string.IsNullOrEmpty(paramList)) { sb.Append(paramList); sb.Append(", "); }
                sb.AppendLine("System.Threading.CancellationToken ct = default)");
                sb.AppendLine("        {");
                sb.Append("            var cmd = new ").Append(cmd.RecordName).Append('(').Append(argList).AppendLine(");");

                if (isQueueable)
                {
                    sb.Append("            return YFex.Cqrs.YFexDispatcherProvider.Current.CommandAsync<");
                    sb.Append(cmd.RecordName).AppendLine(">(cmd, ct);");
                }
                else
                {
                    sb.Append("            return UnwrapVoidAsync_").Append(cmd.MethodName).AppendLine("(cmd, ct);");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.Append("        private static async System.Threading.Tasks.ValueTask<YFex.Cqrs.Result> UnwrapVoidAsync_");
                    sb.Append(cmd.MethodName).Append('(').Append(cmd.RecordName).AppendLine(" cmd, System.Threading.CancellationToken ct)");
                    sb.AppendLine("        {");
                    sb.Append("            var r = await YFex.Cqrs.YFexDispatcherProvider.Current.CommandAsync<");
                    sb.Append(cmd.RecordName).AppendLine(">(cmd, ct).ConfigureAwait(false);");
                    sb.AppendLine("            if (r.TryGetSuccess(out var s)) return s;");
                    sb.AppendLine("            if (r.TryGetError(out var e)) return e;");
                    sb.AppendLine("            return YFex.Cqrs.Result.Fail(\"Command was queued unexpectedly.\");");
                }
            }

            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
    }

    private static void AppendEventsClass(StringBuilder sb, EquatableArray<EventToGenerate> events)
    {
        sb.AppendLine("    public static partial class Events");
        sb.AppendLine("    {");

        bool first = true;
        foreach (var evt in events)
        {
            if (!first) sb.AppendLine();
            first = false;

            // Raise(TEvent e, CancellationToken ct = default)
            sb.Append("        public static System.Threading.Tasks.ValueTask Raise(");
            sb.Append(evt.RecordName);
            sb.AppendLine(" e, System.Threading.CancellationToken ct = default)");
            sb.Append("            => YFex.Cqrs.YFexDispatcherProvider.Current.PublishAsync(e, ct);");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
    }

    // ── Pipeline B: AddYFexConfigurations ─────────────────────────────────────

    public static string GenerateConfigRegistration(System.Collections.Immutable.ImmutableArray<ConfigRegistration> registrations)
    {
        var sb = new StringBuilder(512);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using YFex.Cqrs.Configuration;");
        sb.AppendLine();
        sb.AppendLine("public static class YFexConfigurationRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddYFexConfigurations(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var reg in registrations)
        {
            foreach (var (ifaceName, _) in reg.Interfaces)
            {
                sb.Append("        services.AddSingleton<");
                sb.Append(ifaceName);
                sb.Append(", ");
                sb.Append(reg.ImplementationFqn);
                sb.AppendLine(">();");
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
