using System.Text;

namespace YFex.Cqrs.SourceGenerator;

/// <summary>
/// Generates Fusion RPC contract code for each aggregate when the consumer project
/// defines the <c>YFEX_RPC</c> preprocessor constant (injected via
/// <c>YFex.Messaging.Rpc.targets</c>).
///
/// Emits four output files per aggregate:
/// <list type="number">
///   <item><c>I{Aggregate}RpcContract</c> — Fusion compute-service interface.</item>
///   <item><c>{Aggregate}RpcContractImpl</c> — server-side impl that forwards to <c>IHandlerInvoker</c>.</item>
///   <item><c>{Aggregate}RpcServerRegistration</c> — DI extension to call <c>fusion.AddServer()</c>.</item>
///   <item><c>{Aggregate}RpcClientRegistration</c> — DI extension that populates the <c>FusionMessageBusBuilder</c>.</item>
/// </list>
/// </summary>
internal static class RpcContractCodeBuilder
{
    // ── Entry point ───────────────────────────────────────────────────────────

    public static (string Hint, string Source) GenerateInterface(ClassToGenerate model) =>
        ($"{model.ClassName}RpcContract.g.cs", BuildInterface(model));

    public static (string Hint, string Source) GenerateServerImpl(ClassToGenerate model) =>
        ($"{model.ClassName}RpcContractImpl.g.cs", BuildServerImpl(model));

    public static (string Hint, string Source) GenerateRegistrations(ClassToGenerate model) =>
        ($"{model.ClassName}RpcRegistrations.g.cs", BuildRegistrations(model));

    // ── Interface ─────────────────────────────────────────────────────────────

    private static string BuildInterface(ClassToGenerate model)
    {
        var sb = new StringBuilder(512);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#if YFEX_RPC");
        sb.AppendLine();
        sb.AppendLine("using ActualLab.Fusion;");
        sb.AppendLine("using YFex.Cqrs;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(model.Namespace))
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";").AppendLine();

        string ifaceName = $"I{model.ClassName}RpcContract";
        sb.Append("/// <summary>Fusion compute-service contract for the <c>").Append(model.ClassName)
          .AppendLine("</c> aggregate.</summary>");
        sb.Append("public interface ").Append(ifaceName).AppendLine(" : IComputeService");
        sb.AppendLine("{");

        foreach (var q in model.Queries)
        {
            sb.AppendLine("    /// <summary>Fusion compute-method — result is cached and pushed on invalidation.</summary>");
            sb.AppendLine("    [ComputeMethod]");
            sb.Append("    System.Threading.Tasks.Task<YFex.Cqrs.Result<").Append(q.ReturnType).Append(">> ");
            sb.Append(q.MethodName).Append("(").Append(q.RecordName)
              .AppendLine(" q, System.Threading.CancellationToken ct = default);");
            sb.AppendLine();
        }

        foreach (var cmd in model.Commands)
        {
            sb.AppendLine("    /// <summary>Fusion command-handler — executes once, triggers compute invalidation.</summary>");
            sb.AppendLine("    [CommandHandler]");
            if (!string.IsNullOrEmpty(cmd.ResultType))
            {
                sb.Append("    System.Threading.Tasks.Task<YFex.Cqrs.QueueableResult<")
                  .Append(cmd.ResultType).Append(">> ");
            }
            else
            {
                sb.Append("    System.Threading.Tasks.Task<YFex.Cqrs.QueueableResult> ");
            }
            sb.Append(cmd.MethodName).Append("(").Append(cmd.RecordName)
              .AppendLine(" cmd, System.Threading.CancellationToken ct = default);");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        sb.AppendLine("#endif // YFEX_RPC");
        return sb.ToString();
    }

    // ── Server implementation ─────────────────────────────────────────────────

    private static string BuildServerImpl(ClassToGenerate model)
    {
        var sb = new StringBuilder(1024);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#if YFEX_RPC");
        sb.AppendLine();
        sb.AppendLine("using ActualLab.Fusion;");
        sb.AppendLine("using YFex.Cqrs;");
        sb.AppendLine("using YFex.Messaging.Rpc;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(model.Namespace))
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";").AppendLine();

        string ifaceName  = $"I{model.ClassName}RpcContract";
        string implName   = $"{model.ClassName}RpcContractImpl";

        sb.Append("/// <summary>Server-side Fusion implementation of <see cref=\"").Append(ifaceName)
          .AppendLine("\"/>. Forwards each call to the registered <see cref=\"IHandlerInvoker\"/>.</summary>");
        sb.Append("public class ").Append(implName).Append(" : ").AppendLine(ifaceName);
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IHandlerInvoker _invoker;");
        sb.AppendLine();
        sb.Append("    public ").Append(implName).AppendLine("(IHandlerInvoker invoker) => _invoker = invoker;");

        // Queries → [ComputeMethod] virtual methods
        foreach (var q in model.Queries)
        {
            sb.AppendLine();
            sb.AppendLine("    [ComputeMethod]");
            sb.Append("    public virtual async System.Threading.Tasks.Task<YFex.Cqrs.Result<")
              .Append(q.ReturnType).Append(">> ")
              .Append(q.MethodName)
              .Append("(").Append(q.RecordName).AppendLine(" q, System.Threading.CancellationToken ct = default)");
            sb.AppendLine("    {");
            sb.Append("        var value = await _invoker.InvokeAsync<").Append(q.ReturnType)
              .AppendLine(">(q, ct).ConfigureAwait(false);");
            sb.Append("        return YFex.Cqrs.Result<").Append(q.ReturnType).AppendLine(">.Ok(value);");
            sb.AppendLine("    }");
        }

        // Commands → [CommandHandler] virtual methods with Invalidation.Begin() hook
        foreach (var cmd in model.Commands)
        {
            bool hasResult = !string.IsNullOrEmpty(cmd.ResultType);
            string resultTypeFull = hasResult
                ? $"YFex.Cqrs.QueueableResult<{cmd.ResultType}>"
                : "YFex.Cqrs.QueueableResult";

            sb.AppendLine();
            sb.AppendLine("    [CommandHandler]");
            sb.Append("    public virtual async System.Threading.Tasks.Task<").Append(resultTypeFull).Append("> ")
              .Append(cmd.MethodName)
              .Append("(").Append(cmd.RecordName).AppendLine(" cmd, System.Threading.CancellationToken ct = default)");
            sb.AppendLine("    {");
            // Fusion calls the method inside Invalidation.IsActive to record invalidation deps.
            sb.AppendLine("        if (Invalidation.IsActive)");
            sb.AppendLine("        {");
            sb.AppendLine("            // Override OnInvalidate() to emit compute-method calls that should be invalidated.");
            sb.AppendLine("            OnInvalidate(cmd);");
            sb.Append("            return default(").Append(resultTypeFull).AppendLine(");");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            if (hasResult)
            {
                sb.Append("            var value = await _invoker.InvokeAsync<").Append(cmd.ResultType)
                  .AppendLine(">(cmd, ct).ConfigureAwait(false);");
                // Trigger invalidation after success
                sb.AppendLine("            using (Invalidation.Begin()) OnInvalidate(cmd);");
                sb.Append("            return YFex.Cqrs.QueueableResult<").Append(cmd.ResultType).AppendLine(">.Ok(value);");
            }
            else
            {
                sb.AppendLine("            await _invoker.InvokeAsync(cmd, ct).ConfigureAwait(false);");
                sb.AppendLine("            using (Invalidation.Begin()) OnInvalidate(cmd);");
                sb.AppendLine("            return YFex.Cqrs.QueueableResult.Ok();");
            }
            sb.AppendLine("        }");
            sb.AppendLine("        catch (YFex.Messaging.Rpc.Wolverine.ResultConversionException rce)");
            sb.AppendLine("        {");
            if (hasResult)
                sb.AppendLine("            return rce.TypedError;");
            else
                sb.AppendLine("            return rce.TypedError;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Override to emit compute-method calls that should be invalidated after a command succeeds.");
        sb.AppendLine("    /// Called inside <c>Invalidation.Begin()</c> scope — Fusion records the calls as invalidation targets.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    protected virtual void OnInvalidate(object command) { }");

        sb.AppendLine("}");
        sb.AppendLine("#endif // YFEX_RPC");
        return sb.ToString();
    }

    // ── Server + client registrations ─────────────────────────────────────────

    private static string BuildRegistrations(ClassToGenerate model)
    {
        var sb = new StringBuilder(512);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#if YFEX_RPC");
        sb.AppendLine();
        sb.AppendLine("using ActualLab.Fusion;");
        sb.AppendLine("using YFex.Cqrs;");
        sb.AppendLine("using YFex.Messaging.Rpc;");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(model.Namespace))
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";").AppendLine();

        string ifaceName = $"I{model.ClassName}RpcContract";
        string implName  = $"{model.ClassName}RpcContractImpl";

        // ── Server registration ──
        sb.AppendLine("/// <summary>Generated server-side Fusion registration helpers.</summary>");
        sb.Append("public static class ").Append(model.ClassName).AppendLine("RpcServerRegistration");
        sb.AppendLine("{");
        sb.Append("    /// <summary>Registers <see cref=\"").Append(ifaceName).AppendLine("\"/> on the Fusion server.</summary>");
        sb.Append("    public static FusionBuilder Add").Append(model.ClassName).AppendLine("RpcServer(this FusionBuilder fusion)");
        sb.AppendLine("    {");
        sb.Append("        fusion.AddServer<").Append(ifaceName).Append(", ").Append(implName).AppendLine(">();");
        sb.AppendLine("        return fusion;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // ── Client registration ──
        sb.AppendLine("/// <summary>Generated client-side Fusion registration helpers.</summary>");
        sb.Append("public static class ").Append(model.ClassName).AppendLine("RpcClientRegistration");
        sb.AppendLine("{");
        sb.Append("    /// <summary>Registers the Fusion proxy client and wires the routing table into <see cref=\"FusionMessageBusBuilder\"/>.</summary>");
        sb.AppendLine();
        sb.Append("    public static FusionBuilder Add").Append(model.ClassName).AppendLine("RpcClient(this FusionBuilder fusion)");
        sb.AppendLine("    {");
        sb.Append("        fusion.AddClient<").Append(ifaceName).AppendLine(">();");
        sb.AppendLine("        return fusion;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.Append("    /// <summary>Populates <paramref name=\"builder\"/> with the query/command routing from <see cref=\"");
        sb.Append(ifaceName).AppendLine("\"/>.</summary>");
        sb.Append("    public static void RegisterRoutes(FusionMessageBusBuilder builder, ").Append(ifaceName).AppendLine(" proxy)");
        sb.AppendLine("    {");

        // Register each query
        foreach (var q in model.Queries)
        {
            sb.Append("        builder.AddQuery<").Append(q.RecordName).Append(", ").Append(q.ReturnType).AppendLine(">(");
            sb.Append("            async (q, ct) => { var r = await proxy.").Append(q.MethodName)
              .AppendLine("(q, ct).ConfigureAwait(false);");
            sb.AppendLine("                            if (r.TryGetValue(out var v)) return v!;");
            sb.AppendLine("                            throw new System.InvalidOperationException(\"Query failed.\"); });");
        }

        // Register each command with result
        foreach (var cmd in model.Commands)
        {
            if (!string.IsNullOrEmpty(cmd.ResultType))
            {
                sb.Append("        builder.AddCommand<").Append(cmd.RecordName).Append(", ").Append(cmd.ResultType).AppendLine(">(");
                sb.Append("            async (cmd, ct) => { var r = await proxy.").Append(cmd.MethodName)
                  .AppendLine("(cmd, ct).ConfigureAwait(false);");
                sb.AppendLine("                              if (r.TryGetValue(out var v)) return v!;");
                sb.AppendLine("                              throw new System.InvalidOperationException(\"Command failed.\"); });");
            }
            else
            {
                sb.Append("        builder.AddCommand<").Append(cmd.RecordName).AppendLine(">(");
                sb.Append("            async (cmd, ct) => { await proxy.").Append(cmd.MethodName)
                  .AppendLine("(cmd, ct).ConfigureAwait(false); });");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("#endif // YFEX_RPC");
        return sb.ToString();
    }
}
