<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="YFex.System.Windows" />
    <InternalsVisibleTo Include="YFex.Windows.Security" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Persistence\YFex.Persistence\YFex.Persistence.csproj" />
    <ProjectReference Include="..\..\Persistence\YFex.Persistence.FileSystem\YFex.Persistence.FileSystem.csproj" />
  </ItemGroup>

</Project>
