using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace YFex.State.History.Generator;

internal static class UndoableEmitter
{
    private const string AutoGenHeader  = "// <auto-generated/>";
    private const string GeneratorName  = "YFex.State.History.Generator";
    private const string GeneratorVer   = "1.0.0";

    public static void Emit(SourceProductionContext ctx, UndoableClassModel model)
    {
        if (model.Properties.IsEmpty && model.ExplicitContexts.IsEmpty) return;

        var sb = new StringBuilder(2048);

        sb.AppendLine(AutoGenHeader);
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8625 // null to non-nullable ref");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        // [GeneratedCode] and [ExcludeFromCodeCoverage] are NOT emitted here:
        // only the Observable generator's partial file adds them once per class.
        sb.Append("partial class ").Append(model.ClassName);
        if (!model.TypeParameters.IsEmpty)
        {
            sb.Append('<');
            for (int i = 0; i < model.TypeParameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(model.TypeParameters[i]);
            }
            sb.Append('>');
        }
        if (model.HasSinglePrimaryScope)
            sb.Append(" : global::YFex.State.History.IUndoable");
        sb.AppendLine();
        sb.AppendLine("{");

        // ── Determine all unique context keys ─────────────────────────────────
        // A context key is either: scopeName (Mode B/class-level), propertyName (Mode A), or
        // contextName (Mode C — refers to an existing property).
        var autoContextKeys = new HashSet<string>();      // keys for auto-generated fields
        var explicitContextKeys = new HashSet<string>();  // keys for [UndoContext] properties

        foreach (var ctx2 in model.ExplicitContexts)
            explicitContextKeys.Add(ctx2.PropertyName);

        foreach (var prop in model.Properties)
        {
            if (prop.ContextName is not null) continue; // Mode C — no auto field
            string contextKey = prop.ScopeName ?? prop.PropertyName; // scope or property-isolated
            autoContextKeys.Add(contextKey);
        }

        // ── Auto-created UndoContext fields (Mode A / Mode B) ─────────────────
        if (autoContextKeys.Count > 0)
        {
            sb.AppendLine("    // ── Auto-created undo contexts ────────────────────────────────────");
            foreach (var key in autoContextKeys)
            {
                sb.Append("    private global::YFex.State.History.UndoContext __undoCtx_")
                  .Append(key)
                  .AppendLine(" = new global::YFex.State.History.UndoContext();");
            }
            sb.AppendLine();
        }

        // ── Static setter delegates ───────────────────────────────────────────
        if (!model.Properties.IsEmpty)
        {
            sb.AppendLine("    // ── Static setter delegates (AOT-safe, one per property per class) ─");
            foreach (var prop in model.Properties)
            {
                sb.Append("    private static readonly global::System.Action<object, object?> __undoSetter_")
                  .Append(prop.PropertyName)
                  .AppendLine(" =");
                sb.Append("        static (owner, v) => ((")
                  .Append(model.FullyQualifiedClassName)
                  .Append(")owner).")
                  .Append(prop.PropertyName)
                  .Append(" = (")
                  .Append(prop.FullTypeName)
                  .AppendLine(")v!;");
            }
            sb.AppendLine();
        }

        // ── Lazy batch-observer subscription ─────────────────────────────────
        if (!model.Properties.IsEmpty)
        {
            sb.AppendLine("    // ── Batch-observer subscription (lazy, wired on first change) ────");
            sb.AppendLine("    private global::YFex.State.History.UndoBatchObserver? __undoBatchObserver;");
            sb.AppendLine();
            sb.AppendLine("    private void __EnsureUndoSubscribed()");
            sb.AppendLine("    {");
            sb.AppendLine("        if (__undoBatchObserver is not null) return;");
            sb.AppendLine("        __undoBatchObserver = new global::YFex.State.History.UndoBatchObserver(");
            sb.AppendLine("            this, __GetAllUndoContexts());");
            sb.AppendLine("    }");
            sb.AppendLine();

            // __GetAllUndoContexts — deduplicated array of all contexts
            sb.AppendLine("    private global::YFex.State.History.UndoContext[] __GetAllUndoContexts()");
            sb.Append("        => [");
            bool first = true;
            foreach (var key in autoContextKeys)
            {
                if (!first) sb.Append(", ");
                sb.Append("__undoCtx_").Append(key);
                first = false;
            }
            foreach (var ctx2 in model.ExplicitContexts)
            {
                if (!first) sb.Append(", ");
                sb.Append(ctx2.PropertyName);
                first = false;
            }
            sb.AppendLine("];");
            sb.AppendLine();
        }

        // ── OnXxxChanging partial implementations ──────────────────────────────
        if (!model.Properties.IsEmpty)
        {
            sb.AppendLine("    // ── Undo delta capture (OnXxxChanging hooks) ─────────────────────");
            foreach (var prop in model.Properties)
            {
                string ctxExpr = prop.ContextName is not null
                    ? prop.ContextName
                    : $"__undoCtx_{prop.ScopeName ?? prop.PropertyName}";

                sb.Append("    partial void On").Append(prop.PropertyName).Append("Changing(")
                  .Append(prop.FullTypeName).Append(" oldValue, ")
                  .Append(prop.FullTypeName).AppendLine(" newValue)");
                sb.AppendLine("    {");
                sb.Append("        if (").Append(ctxExpr).AppendLine(".IsReplaying || ")
                  .Append("            ").Append(ctxExpr).AppendLine(".IsSuspended) return;");
                sb.AppendLine("        __EnsureUndoSubscribed();");
                sb.Append("        ").Append(ctxExpr).AppendLine(".RecordPropertyChange(");
                sb.AppendLine("            this,");
                sb.Append("            \"").Append(prop.PropertyName).AppendLine("\",");
                sb.Append("            __undoSetter_").Append(prop.PropertyName).AppendLine(",");
                sb.AppendLine("            oldValue,");
                sb.AppendLine("            newValue,");
                sb.AppendLine("            global::System.DateTime.UtcNow.Ticks,");
                sb.Append("            ").Append(prop.MergeWindowMs).AppendLine(");");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        // ── Command wrapper properties ─────────────────────────────────────────
        sb.AppendLine("    // ── Undo/Redo command wrappers ────────────────────────────────────────");

        // Auto-created context commands (Mode A / B)
        foreach (var key in autoContextKeys)
        {
            string prefix = model.Properties.Length == 1 &&
                            autoContextKeys.Count == 1 &&
                            model.ExplicitContexts.IsEmpty
                ? string.Empty // single scope: plain UndoCommand / RedoCommand via IUndoable
                : $"{key}";

            sb.Append("    public global::YFex.State.Commands.IStateCommand ").Append(key)
              .AppendLine("UndoCommand");
            sb.Append("        => __undoCtx_").Append(key).AppendLine(".UndoCommand;");

            sb.Append("    public global::YFex.State.Commands.IStateCommand ").Append(key)
              .AppendLine("RedoCommand");
            sb.Append("        => __undoCtx_").Append(key).AppendLine(".RedoCommand;");
            sb.AppendLine();
        }

        // Explicit context commands (Mode C)
        foreach (var ctx2 in model.ExplicitContexts)
        {
            sb.Append("    public global::YFex.State.Commands.IStateCommand ").Append(ctx2.PropertyName)
              .AppendLine("UndoCommand");
            sb.Append("        => ").Append(ctx2.PropertyName).AppendLine(".UndoCommand;");

            sb.Append("    public global::YFex.State.Commands.IStateCommand ").Append(ctx2.PropertyName)
              .AppendLine("RedoCommand");
            sb.Append("        => ").Append(ctx2.PropertyName).AppendLine(".RedoCommand;");
            sb.AppendLine();
        }

        // ── IUndoable implementation (single primary scope only) ──────────────
        if (model.HasSinglePrimaryScope)
        {
            sb.AppendLine("    // ── IUndoable ─────────────────────────────────────────────────────────");

            string historyExpr;
            if (!model.ExplicitContexts.IsEmpty)
                historyExpr = model.ExplicitContexts[0].PropertyName;
            else if (autoContextKeys.Count > 0)
            {
                // Pick the single key
                string? single = null;
                foreach (var k in autoContextKeys) { single = k; break; }
                historyExpr = $"__undoCtx_{single}";
            }
            else
            {
                historyExpr = "null!";
            }

            sb.AppendLine($"    global::YFex.State.History.UndoContext global::YFex.State.History.IUndoable.UndoHistory");
            sb.Append("        => ").Append(historyExpr).AppendLine(";");

            sb.AppendLine("    global::YFex.State.Commands.IStateCommand global::YFex.State.History.IUndoable.UndoCommand");
            sb.Append("        => ").Append(historyExpr).AppendLine(".UndoCommand;");

            sb.AppendLine("    global::YFex.State.Commands.IStateCommand global::YFex.State.History.IUndoable.RedoCommand");
            sb.Append("        => ").Append(historyExpr).AppendLine(".RedoCommand;");

            // Add IUndoable to the partial class interface list
            // (Done by emitting it as an explicit implementation above; the interface itself
            //  is declared in the class declaration — we can't add it here without changing
            //  the class declaration syntax. V2: emit a separate base list partial.)
            sb.AppendLine();
        }

        sb.AppendLine("}");

        string hintName = string.IsNullOrEmpty(model.Namespace)
            ? $"{model.ClassName}.History.g.cs"
            : $"{model.Namespace}.{model.ClassName}.History.g.cs";

        ctx.AddSource(hintName, sb.ToString());
    }
}
