using System.Text;
using System.Text.Json;
using YFex.Security.Storage;

namespace YFex.Security.ApiReverser;

/// <summary>
/// [PERSONAL USE] Generates a dependency-free C# <c>HttpClient</c> wrapper from cataloged
/// API endpoints. Emitted code uses only System.Net.Http + System.Text.Json.
/// </summary>
public sealed class ClientCodeGenerator
{
    private readonly IApiCatalogRepository _catalog;

    public ClientCodeGenerator(IApiCatalogRepository catalog)
    {
        _catalog = catalog;
    }

    public async Task<string> GenerateClientCodeAsync(string serviceName, CancellationToken ct = default)
    {
        var endpoints = await _catalog.GetEndpointsAsync(serviceName, ct);
        string className = ToPascalCase(serviceName) + "Client";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> Generated by YFex.Security.ApiReverser. </auto-generated>");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace Generated.{ToPascalCase(serviceName)};");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {className}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly HttpClient _http;");
        sb.AppendLine();
        sb.AppendLine($"    public {className}(HttpClient http) => _http = http;");
        sb.AppendLine();

        // Auth helper if any endpoint declares auth.
        var authEndpoint = endpoints.FirstOrDefault(e => e.AuthType is not null);
        if (authEndpoint?.AuthType is { } authType)
            EmitAuthSetup(sb, authType, authEndpoint);

        var usedNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var endpoint in endpoints)
        {
            string methodName = UniqueName(BuildMethodName(endpoint.Method, endpoint.PathTemplate), usedNames);
            EmitEndpointMethod(sb, endpoint, methodName);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    public async Task WriteClientFileAsync(string serviceName, string outputPath, CancellationToken ct = default)
    {
        string code = await GenerateClientCodeAsync(serviceName, ct);
        string? dir = Path.GetDirectoryName(outputPath);
        if (dir is not null && !Directory.Exists(dir))
            Directory.CreateDirectory(dir);
        await File.WriteAllTextAsync(outputPath, code, ct);
    }

    private static void EmitAuthSetup(StringBuilder sb, string authType, ApiEndpointRecord endpoint)
    {
        switch (authType)
        {
            case "OAuth2/Bearer":
            case "OAuth2/OIDC":
                sb.AppendLine("    /// <summary>Set the bearer token used for all subsequent requests.</summary>");
                sb.AppendLine("    public void SetBearerToken(string token) =>");
                sb.AppendLine("        _http.DefaultRequestHeaders.Authorization =");
                sb.AppendLine("            new System.Net.Http.Headers.AuthenticationHeaderValue(\"Bearer\", token);");
                sb.AppendLine();
                break;
            case "ApiKey":
                string headerName = endpoint.AuthDetails ?? "X-Api-Key";
                sb.AppendLine("    /// <summary>Set the API key sent with every request.</summary>");
                sb.AppendLine("    public void SetApiKey(string apiKey) =>");
                sb.AppendLine($"        _http.DefaultRequestHeaders.Add(\"{headerName}\", apiKey);");
                sb.AppendLine();
                break;
            case "Cookie":
                sb.AppendLine("    // Cookie auth: configure HttpClientHandler.CookieContainer when constructing HttpClient.");
                sb.AppendLine();
                break;
        }
    }

    private static void EmitEndpointMethod(StringBuilder sb, ApiEndpointRecord endpoint, string methodName)
    {
        var pathParams = ExtractPathParams(endpoint.PathTemplate);
        bool hasBody = endpoint.Method is "POST" or "PUT" or "PATCH";

        var paramList = new List<string>();
        foreach (var p in pathParams) paramList.Add($"string {p}");
        if (hasBody) paramList.Add("object? body = null");
        paramList.Add("CancellationToken ct = default");

        // Build interpolated path.
        string interpolatedPath = endpoint.PathTemplate;
        foreach (var p in pathParams)
            interpolatedPath = interpolatedPath.Replace($"{{{p}}}", $"{{{p}}}");

        sb.AppendLine($"    /// <summary>{endpoint.Method} {endpoint.PathTemplate} ({endpoint.CallCount} call(s) observed)</summary>");
        sb.AppendLine($"    public async Task<JsonDocument> {methodName}({string.Join(", ", paramList)})");
        sb.AppendLine("    {");
        sb.AppendLine($"        var request = new HttpRequestMessage(HttpMethod.{ToHttpMethod(endpoint.Method)}, $\"{interpolatedPath}\");");

        if (hasBody)
            sb.AppendLine("        if (body is not null) request.Content = JsonContent.Create(body);");

        sb.AppendLine("        using var response = await _http.SendAsync(request, ct);");
        sb.AppendLine("        response.EnsureSuccessStatusCode();");
        sb.AppendLine("        await using var stream = await response.Content.ReadAsStreamAsync(ct);");
        sb.AppendLine("        return await JsonDocument.ParseAsync(stream, default, ct);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static List<string> ExtractPathParams(string template)
    {
        var result = new List<string>();
        int idx = 0;
        while ((idx = template.IndexOf('{', idx)) >= 0)
        {
            int end = template.IndexOf('}', idx);
            if (end < 0) break;
            result.Add(template.Substring(idx + 1, end - idx - 1));
            idx = end + 1;
        }
        return result;
    }

    private static string BuildMethodName(string method, string pathTemplate)
    {
        var segments = pathTemplate.Trim('/').Split('/', StringSplitOptions.RemoveEmptyEntries);
        var sb = new StringBuilder(ToPascalCase(method.ToLowerInvariant()));

        foreach (var segment in segments)
        {
            if (segment.StartsWith('{'))
                sb.Append("By").Append(ToPascalCase(segment.Trim('{', '}').Replace("param_", "p")));
            else
                sb.Append(ToPascalCase(segment));
        }

        return sb.Length > 0 ? sb.ToString() : "Invoke";
    }

    private static string UniqueName(string name, HashSet<string> used)
    {
        if (used.Add(name)) return name;
        int i = 2;
        while (!used.Add($"{name}{i}")) i++;
        return $"{name}{i}";
    }

    private static string ToHttpMethod(string method) => method.ToUpperInvariant() switch
    {
        "GET" => "Get",
        "POST" => "Post",
        "PUT" => "Put",
        "DELETE" => "Delete",
        "PATCH" => "Patch",
        "HEAD" => "Head",
        "OPTIONS" => "Options",
        _ => "Get"
    };

    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input)) return "";
        var parts = input.Split(['-', '_', '.', ' '], StringSplitOptions.RemoveEmptyEntries);
        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            if (part.Length == 0) continue;
            sb.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1) sb.Append(part[1..]);
        }
        return sb.Length > 0 ? sb.ToString() : input;
    }
}
