<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\YFex.Security\YFex.Security.csproj" />
    <ProjectReference Include="..\YFex.Security.Storage\YFex.Security.Storage.csproj" />
  </ItemGroup>

</Project>
