<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0-windows</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>yfex-security</AssemblyName>
    <RootNamespace>YFex.Security.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\YFex.Security\YFex.Security.csproj" />
    <ProjectReference Include="..\YFex.Security.Storage\YFex.Security.Storage.csproj" />
    <ProjectReference Include="..\YFex.Security.Analysis\YFex.Security.Analysis.csproj" />
    <ProjectReference Include="..\YFex.Security.Service\YFex.Security.Service.csproj" />
  </ItemGroup>

</Project>
