using System.Text;
using Microsoft.CodeAnalysis;

namespace YFex.State.Generator;

/// <summary>
/// Emits the partial class implementation for [StateCommand]-marked methods.
/// For each method emits:
///   - A private CancellationTokenSource field (when HasCancellationToken).
///   - A private nested command class implementing IAsyncStateCommand + INotifyPropertyChanged
///     (async) or IStateCommand (sync).
///   - A public lazy-init property exposing the command.
///   - For ValueTask / ValueTask&lt;T&gt;: a zero-flicker fast path that skips the Executing
///     transition when the ValueTask completes synchronously.
///   - For Task&lt;T&gt; / ValueTask&lt;T&gt; with TargetProperty: automatic result flattening
///     into the named [Observable] property after successful execution.
/// </summary>
internal static class CommandEmitter
{
    private const string AutoGenHeader = "// <auto-generated/>";
    private const string GeneratorName = "YFex.State.Generator";
    private const string GeneratorVersion = "1.0.0";

    // Fully-qualified names used in generated code
    private const string Ns = "global::YFex.State.Commands.";
    private const string SysComp = "global::System.ComponentModel.";
    private const string SysThr = "global::System.Threading.";
    private const string SysThrTasks = "global::System.Threading.Tasks.";
    private const string Sys = "global::System.";

    public static void Emit(SourceProductionContext ctx, CommandClassModel model)
    {
        if (model.Methods.Length == 0) return;

        var sb = new StringBuilder(1024);

        sb.AppendLine(AutoGenHeader);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        // Note: [GeneratedCode] and [ExcludeFromCodeCoverage] are NOT emitted on the partial class
        // declaration here — they are already on the .Observable.g.cs partial. Emitting them twice
        // on different partial declarations of the same class causes CS0579 (duplicate attribute).
        sb.Append("partial class ").Append(model.ClassName);
        if (!model.TypeParameters.IsEmpty)
        {
            sb.Append('<');
            for (int i = 0; i < model.TypeParameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(model.TypeParameters[i]);
            }
            sb.Append('>');
        }
        sb.AppendLine();
        sb.AppendLine("{");

        foreach (var method in model.Methods)
            EmitCommand(sb, method);

        sb.AppendLine("}");

        string hintName = string.IsNullOrEmpty(model.Namespace)
            ? model.ClassName + ".Commands.g.cs"
            : model.Namespace + "." + model.ClassName + ".Commands.g.cs";

        ctx.AddSource(hintName, sb.ToString());
    }

    private static void EmitCommand(StringBuilder sb, CommandMethodRawModel m)
    {
        sb.AppendLine();
        sb.Append("    // ── ").Append(m.CommandPropertyName)
          .AppendLine(" ─────────────────────────────────────────────");

        if (m.IsAsync)
            EmitAsyncCommand(sb, m);
        else
            EmitSyncCommand(sb, m);
    }

    // ── Async command ──────────────────────────────────────────────────────────

    private static void EmitAsyncCommand(StringBuilder sb, CommandMethodRawModel m)
    {
        string cmdField = "__cmd_" + m.CommandPropertyName;
        string executingField = "__executing_" + m.CommandPropertyName;
        string ctsField = m.HasCancellationToken ? "__cts_" + m.CommandPropertyName : string.Empty;
        string cmdClass = "__AsyncCmd_" + m.CommandPropertyName;
        string cancelClass = "__CancelCmd_" + m.CommandPropertyName;

        bool isValueTask = m.ReturnKind == ReturnTypeKind.ValueTask
                        || m.ReturnKind == ReturnTypeKind.ValueTaskOfT;
        bool hasResult = m.ReturnKind == ReturnTypeKind.TaskOfT
                      || m.ReturnKind == ReturnTypeKind.ValueTaskOfT;
        bool autoFlatten = hasResult && m.TargetPropertyName is not null;

        // ── Fields ────────────────────────────────────────────────────────────

        if (m.HasCancellationToken)
            sb.Append("    private ").Append(SysThr).Append("CancellationTokenSource? ")
              .Append(ctsField).AppendLine(";");

        sb.Append("    private int ").Append(executingField).AppendLine("; // 0=idle 1=running");
        sb.Append("    private ").Append(Ns).Append("IAsyncStateCommand? ").Append(cmdField).AppendLine(";");

        // ── Public command property ───────────────────────────────────────────

        sb.AppendLine();
        sb.Append("    public ").Append(Ns).Append("IAsyncStateCommand ").AppendLine(m.CommandPropertyName);
        sb.Append("        => ").Append(cmdField).Append(" ??= new ").Append(cmdClass).AppendLine("(this);");

        // ── Cancel command property (optional) ────────────────────────────────

        if (m.IncludeCancelCommand)
        {
            sb.AppendLine();
            string cancelField = "__cmd_" + m.CancelCommandName;
            sb.Append("    private ").Append(Ns).Append("IStateCommand? ").Append(cancelField).AppendLine(";");
            sb.Append("    public ").Append(Ns).Append("IStateCommand ").AppendLine(m.CancelCommandName);
            sb.Append("        => ").Append(cancelField).Append(" ??= new ")
              .Append(cancelClass).AppendLine("(this);");
        }

        // ── Private command class ─────────────────────────────────────────────

        sb.AppendLine();
        sb.Append("    private sealed class ").Append(cmdClass)
          .Append(" : ").Append(Ns).Append("IAsyncStateCommand, ")
          .Append(SysComp).AppendLine("INotifyPropertyChanged");
        sb.AppendLine("    {");
        sb.Append("        private readonly ").Append(m.ClassName).AppendLine(" _owner;");
        sb.Append("        internal ").Append(cmdClass).Append('(').Append(m.ClassName)
          .AppendLine(" owner) => _owner = owner;");
        sb.AppendLine();

        // PropertyChanged event + Status static args
        sb.Append("        public event ").Append(SysComp).AppendLine("PropertyChangedEventHandler? PropertyChanged;");
        sb.Append("        private static readonly ").Append(SysComp)
          .AppendLine("PropertyChangedEventArgs __statusArgs = new(nameof(Status));");
        sb.AppendLine();

        // CanExecuteChanged event
        sb.AppendLine("        public event global::System.Action? CanExecuteChanged;");
        sb.AppendLine("        internal void NotifyCanExecuteChanged() => CanExecuteChanged?.Invoke();");
        sb.AppendLine();

        // _status field + Status property
        sb.Append("        private ").Append(Ns).Append("CommandStatus _status;");
        sb.AppendLine();
        sb.Append("        public ").Append(Ns).AppendLine("CommandStatus Status");
        sb.AppendLine("        {");
        sb.AppendLine("            get => _status;");
        sb.AppendLine("            private set");
        sb.AppendLine("            {");
        sb.AppendLine("                if (_status == value) return;");
        sb.AppendLine("                _status = value;");
        sb.AppendLine("                PropertyChanged?.Invoke(this, __statusArgs);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // IsExecuting — derived from Status; no second atomic read needed
        sb.Append("        public bool IsExecuting => _status == ")
          .Append(Ns).AppendLine("CommandStatus.Executing;");
        sb.AppendLine("        public bool CanExecute() => !IsExecuting;");
        sb.AppendLine("        public void Execute() { _ = ExecuteAsync(); }");
        sb.AppendLine();

        // ── ExecuteAsync ──────────────────────────────────────────────────────
        sb.Append("        public async ").Append(SysThrTasks).AppendLine("Task ExecuteAsync(");
        sb.Append("            ").Append(SysThr).AppendLine("CancellationToken ct = default)");
        sb.AppendLine("        {");

        // CAS gate — lock-free single-execution guarantee
        sb.Append("            if (").Append(Sys)
          .Append("Threading.Interlocked.CompareExchange(ref _owner.").Append(executingField)
          .AppendLine(", 1, 0) != 0) return;");
        sb.AppendLine();

        if (m.HasCancellationToken)
        {
            sb.Append("            _owner.").Append(ctsField).AppendLine("?.Dispose();");
            sb.Append("            _owner.").Append(ctsField).Append(" = ")
              .Append(SysThr).AppendLine("CancellationTokenSource.CreateLinkedTokenSource(ct);");
        }

        sb.AppendLine("            CanExecuteChanged?.Invoke();");
        if (m.IncludeCancelCommand)
            sb.Append("            (_owner.").Append(m.CancelCommandName)
              .Append(" as ").Append(cancelClass).AppendLine(")?.NotifyCanExecuteChanged();");
        sb.AppendLine();

        // try/finally wraps everything so the CAS release always fires
        sb.AppendLine("            try");
        sb.AppendLine("            {");

        if (isValueTask)
            EmitValueTaskBody(sb, m, hasResult, autoFlatten, ctsField);
        else
            EmitTaskBody(sb, m, hasResult, autoFlatten, ctsField);

        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.Append("                ").Append(Sys)
          .Append("Threading.Interlocked.Exchange(ref _owner.").Append(executingField).AppendLine(", 0);");
        sb.AppendLine("                CanExecuteChanged?.Invoke();");
        if (m.IncludeCancelCommand)
            sb.Append("                (_owner.").Append(m.CancelCommandName)
              .Append(" as ").Append(cancelClass).AppendLine(")?.NotifyCanExecuteChanged();");
        sb.AppendLine("            }");

        sb.AppendLine("        }"); // end ExecuteAsync

        // HandleFault helper
        sb.AppendLine();
        sb.AppendLine("        private void HandleFault(global::System.Exception ex)");
        sb.AppendLine("        {");
        sb.Append("            Status = ").Append(Ns).AppendLine("CommandStatus.Faulted;");
        // Future: route to [ErrorBucket]
        sb.AppendLine("        }");

        sb.AppendLine("    }"); // end command class

        // ── Cancel command class (optional) ───────────────────────────────────

        if (m.IncludeCancelCommand)
            EmitCancelCommandClass(sb, m, cancelClass, ctsField);
    }

    private static void EmitValueTaskBody(
        StringBuilder sb, CommandMethodRawModel m,
        bool hasResult, bool autoFlatten, string ctsField)
    {
        // Build the return type string
        string vtType = hasResult
            ? SysThrTasks + "ValueTask<" + m.ResultTypeName + ">"
            : SysThrTasks + "ValueTask";

        // Invoke the user method — early-exit on synchronous exception
        sb.Append("                ").Append(vtType).AppendLine(" __task;");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        sb.Append("                    __task = _owner.").Append(m.MethodName).Append('(');
        if (m.HasCancellationToken)
            sb.Append("_owner.").Append(ctsField).Append("!.Token");
        sb.AppendLine(");");
        sb.AppendLine("                }");
        sb.AppendLine("                catch (global::System.Exception __ex)");
        sb.AppendLine("                { HandleFault(__ex); return; }");
        sb.AppendLine();

        // ── FAST PATH: ValueTask completed synchronously — zero flicker ───────
        sb.AppendLine("                // ValueTask fast path: no Executing notification when already done.");
        sb.AppendLine("                if (__task.IsCompletedSuccessfully)");
        sb.AppendLine("                {");
        if (autoFlatten)
            sb.Append("                    _owner.").Append(m.TargetPropertyName!)
              .AppendLine(" = __task.Result;");
        sb.Append("                    Status = ").Append(Ns).AppendLine("CommandStatus.Succeeded;");
        sb.AppendLine("                    return;");
        sb.AppendLine("                }");
        sb.AppendLine();

        // ── SLOW PATH: actually yielded ───────────────────────────────────────
        sb.Append("                Status = ").Append(Ns).AppendLine("CommandStatus.Executing;");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        if (hasResult)
        {
            // ConfigureAwait(true) to return to the SynchronizationContext
            // so the ViewModel property assignment stays on the owning thread.
            sb.Append("                    ").Append(m.ResultTypeName!)
              .AppendLine(" __result = await __task.ConfigureAwait(true);");
            if (autoFlatten)
                sb.Append("                    _owner.").Append(m.TargetPropertyName!)
                  .AppendLine(" = __result;");
        }
        else
        {
            sb.AppendLine("                    await __task.ConfigureAwait(true);");
        }
        sb.Append("                    Status = ").Append(Ns).AppendLine("CommandStatus.Succeeded;");
        sb.AppendLine("                }");
        sb.AppendLine("                catch (global::System.OperationCanceledException)");
        sb.Append("                { Status = ").Append(Ns).AppendLine("CommandStatus.Canceled; }");
        sb.AppendLine("                catch (global::System.Exception __ex)");
        sb.AppendLine("                { HandleFault(__ex); }");
    }

    private static void EmitTaskBody(
        StringBuilder sb, CommandMethodRawModel m,
        bool hasResult, bool autoFlatten, string ctsField)
    {
        // For Task / Task<T>: no fast path, but we still track Status.
        sb.Append("                Status = ").Append(Ns).AppendLine("CommandStatus.Executing;");
        sb.AppendLine("                try");
        sb.AppendLine("                {");
        if (hasResult)
        {
            sb.Append("                    ").Append(m.ResultTypeName!)
              .Append(" __result = await _owner.").Append(m.MethodName).Append('(');
            if (m.HasCancellationToken)
                sb.Append("_owner.").Append(ctsField).Append("!.Token");
            sb.AppendLine(").ConfigureAwait(false);");
            if (autoFlatten)
                sb.Append("                    _owner.").Append(m.TargetPropertyName!)
                  .AppendLine(" = __result;");
        }
        else
        {
            sb.Append("                    await _owner.").Append(m.MethodName).Append('(');
            if (m.HasCancellationToken)
                sb.Append("_owner.").Append(ctsField).Append("!.Token");
            sb.AppendLine(").ConfigureAwait(false);");
        }
        sb.Append("                    Status = ").Append(Ns).AppendLine("CommandStatus.Succeeded;");
        sb.AppendLine("                }");
        sb.AppendLine("                catch (global::System.OperationCanceledException)");
        sb.Append("                { Status = ").Append(Ns).AppendLine("CommandStatus.Canceled; }");
        sb.AppendLine("                catch (global::System.Exception __ex)");
        sb.AppendLine("                { HandleFault(__ex); }");
    }

    private static void EmitCancelCommandClass(
        StringBuilder sb, CommandMethodRawModel m, string cancelClass, string ctsField)
    {
        string primaryCmdClass = "__AsyncCmd_" + m.CommandPropertyName;

        sb.AppendLine();
        sb.Append("    private sealed class ").Append(cancelClass)
          .Append(" : ").Append(Ns).AppendLine("IStateCommand");
        sb.AppendLine("    {");
        sb.Append("        private readonly ").Append(m.ClassName).AppendLine(" _owner;");
        sb.Append("        internal ").Append(cancelClass).Append('(').Append(m.ClassName)
          .AppendLine(" owner) => _owner = owner;");
        sb.AppendLine("        public event global::System.Action? CanExecuteChanged;");
        sb.AppendLine("        internal void NotifyCanExecuteChanged() => CanExecuteChanged?.Invoke();");
        sb.Append("        public bool CanExecute() => (_owner.").Append(m.CommandPropertyName)
          .Append(" as ").Append(primaryCmdClass).AppendLine(")?.IsExecuting ?? false;");
        sb.AppendLine("        public void Execute()");
        sb.AppendLine("        {");
        sb.Append("            _owner.").Append(ctsField).AppendLine("?.Cancel();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    // ── Sync command ───────────────────────────────────────────────────────────

    private static void EmitSyncCommand(StringBuilder sb, CommandMethodRawModel m)
    {
        string cmdField = "__cmd_" + m.CommandPropertyName;
        string cmdClass = "__SyncCmd_" + m.CommandPropertyName;

        sb.Append("    private ").Append(Ns).Append("IStateCommand? ").Append(cmdField).AppendLine(";");
        sb.AppendLine();
        sb.Append("    public ").Append(Ns).Append("IStateCommand ").AppendLine(m.CommandPropertyName);
        sb.AppendLine("        => " + cmdField + " ??= new " + cmdClass + "(this);");

        sb.AppendLine();
        sb.Append("    private sealed class ").Append(cmdClass)
          .Append(" : ").Append(Ns).AppendLine("IStateCommand");
        sb.AppendLine("    {");
        sb.Append("        private readonly ").Append(m.ClassName).AppendLine(" _owner;");
        sb.Append("        internal ").Append(cmdClass).Append('(').Append(m.ClassName)
          .AppendLine(" owner) => _owner = owner;");
        sb.AppendLine("        public event global::System.Action? CanExecuteChanged;");
        sb.AppendLine("        public bool CanExecute() => true;");
        sb.Append("        public void Execute() => _owner.").Append(m.MethodName).AppendLine("();");
        sb.AppendLine("    }");
    }
}
