using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace YFex.State.Generator;

/// <summary>
/// Emits the partial class implementation for all [Observable] properties in one class.
/// Uses StringBuilder — never SyntaxFactory or NormalizeWhitespace.
/// </summary>
internal static class ObservableEmitter
{
    private const string AutoGenHeader = "// <auto-generated/>";
    private const string GeneratorName = "YFex.State.Generator";
    private const string GeneratorVersion = "1.0.0";

    public static void Emit(SourceProductionContext ctx, ObservableClassModel model)
    {
        var sb = new StringBuilder(2048);

        sb.AppendLine(AutoGenHeader);
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8618 // backing fields are set via property setters");
        sb.AppendLine("#pragma warning disable CS0649 // read-only [Observable] backing field (use [Computed] for derived values)");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using System.CodeDom.Compiler;");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("[GeneratedCode(\"").Append(GeneratorName).Append("\", \"").Append(GeneratorVersion).AppendLine("\")]");
        sb.AppendLine("[ExcludeFromCodeCoverage]");

        sb.Append("partial class ").Append(model.ClassName);
        if (!model.TypeParameters.IsEmpty)
        {
            sb.Append('<');
            for (int i = 0; i < model.TypeParameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(model.TypeParameters[i]);
            }
            sb.Append('>');
        }
        sb.AppendLine();
        sb.AppendLine("{");

        // ── Static descriptor fields ─────────────────────────────────────────
        sb.AppendLine("    // ── Property change descriptors (compile-time cached) ──────────────");
        foreach (var prop in model.Properties)
        {
            sb.Append("    private static readonly global::YFex.State.Notification.ChangedNotification __desc_")
              .Append(prop.PropertyName)
              .Append(" = new() { PropertyName = \"")
              .Append(prop.PropertyName)
              .Append("\", PropertyId = ")
              .Append(prop.PropertyId)
              .AppendLine("u };");
        }

        // ── DispatchPending override ─────────────────────────────────────────
        // Each class handles only its own property IDs in the switch, then calls
        // base.DispatchPending(mask) so ancestor IDs are handled up the chain.
        // This is safe even when parent has no [Observable] properties — StateObject's
        // base implementation is a no-op.
        sb.AppendLine();
        sb.AppendLine("    // ── Batch dispatch ────────────────────────────────────────────────────");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    protected override void DispatchPending(in global::YFex.State.Internal.PropertyBitmap64 mask)");
        sb.AppendLine("    {");
        sb.AppendLine("        var copy = mask;");
        sb.AppendLine("        while (!copy.IsEmpty())");
        sb.AppendLine("        {");
        sb.AppendLine("            uint id = copy.PopLowest();");
        sb.AppendLine("            switch (id)");
        sb.AppendLine("            {");
        foreach (var prop in model.Properties)
        {
            sb.Append("                case ").Append(prop.PropertyId)
              .Append("u: FireNotification(in __desc_")
              .Append(prop.PropertyName).AppendLine("); break;");
        }
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        base.DispatchPending(in mask);");
        sb.AppendLine("    }");

        // ── MVVM PropertyChangedEventArgs + PropertyChangingEventArgs caches ────
        // Emitted per concrete class so the cache length always matches the class's own
        // property count. Both GetPropertyChangedArgs and GetPropertyChangingArgs form
        // virtual chains: each override handles its own ID range and delegates to base.
        if (model.IsMvvm && model.Properties.Length > 0)
        {
            uint idBase = model.ParentPropertyCount;
            uint idEnd = idBase + (uint)model.Properties.Length;

            sb.AppendLine();
            sb.AppendLine("    // ── MVVM args caches (per-class, never shared with subclasses) ──────");

            // Post-change args
            sb.AppendLine("    private static readonly global::System.ComponentModel.PropertyChangedEventArgs[] __mvvmArgsCache");
            sb.Append("        = new global::System.ComponentModel.PropertyChangedEventArgs[] { ");
            foreach (var prop in model.Properties)
                sb.Append("new(\"").Append(prop.PropertyName).Append("\"), ");
            sb.AppendLine("};");
            sb.AppendLine();
            sb.AppendLine("    protected override global::System.ComponentModel.PropertyChangedEventArgs GetPropertyChangedArgs(uint id)");
            sb.Append("        => id >= ").Append(idBase).Append("u && id < ").Append(idEnd).AppendLine("u");
            sb.Append("            ? __mvvmArgsCache[id - ").Append(idBase).AppendLine("u]");
            sb.AppendLine("            : base.GetPropertyChangedArgs(id);");

            // Pre-change args
            sb.AppendLine();
            sb.AppendLine("    private static readonly global::System.ComponentModel.PropertyChangingEventArgs[] __mvvmChangingArgsCache");
            sb.Append("        = new global::System.ComponentModel.PropertyChangingEventArgs[] { ");
            foreach (var prop in model.Properties)
                sb.Append("new(\"").Append(prop.PropertyName).Append("\"), ");
            sb.AppendLine("};");
            sb.AppendLine();
            sb.AppendLine("    protected override global::System.ComponentModel.PropertyChangingEventArgs GetPropertyChangingArgs(uint id)");
            sb.Append("        => id >= ").Append(idBase).Append("u && id < ").Append(idEnd).AppendLine("u");
            sb.Append("            ? __mvvmChangingArgsCache[id - ").Append(idBase).AppendLine("u]");
            sb.AppendLine("            : base.GetPropertyChangingArgs(id);");
        }

        // ── Activation cascading overrides ───────────────────────────────────
        var activatableProps = FilterProperties(model.Properties,
            static p => p.ParticipatesInActivation && !p.IsReadOnly);
        if (activatableProps.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    // ── Activation cascade ───────────────────────────────────────────────");
            sb.AppendLine("    protected override void OnActivateCascading()");
            sb.AppendLine("    {");
            sb.AppendLine("        base.OnActivateCascading();");
            foreach (var p in activatableProps)
            {
                string access = p.IsNullableActivatable ? $"{p.PropertyName}?" : p.PropertyName;
                sb.Append("        ").Append(access).AppendLine(".Activate();");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    protected override void OnDeactivateCascading()");
            sb.AppendLine("    {");
            foreach (var p in activatableProps)
            {
                string access = p.IsNullableActivatable ? $"{p.PropertyName}?" : p.PropertyName;
                sb.Append("        ").Append(access).AppendLine(".Deactivate();");
            }
            sb.AppendLine("        base.OnDeactivateCascading();");
            sb.AppendLine("    }");
        }

        // ── Validation helpers ───────────────────────────────────────────────
        var validatedProps = FilterProperties(model.Properties,
            static p => !p.ValidatorTypes.IsEmpty || !p.AsyncValidatorTypes.IsEmpty);
        if (validatedProps.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    // ── Validation helpers ───────────────────────────────────────────────");
            foreach (var vp in validatedProps)
                EmitValidationHelper(sb, vp);
        }

        // ── Property implementations ─────────────────────────────────────────
        foreach (var prop in model.Properties)
        {
            sb.AppendLine();
            EmitProperty(sb, prop);
        }

        sb.AppendLine("}");

        string hintName = string.IsNullOrEmpty(model.Namespace)
            ? model.ClassName + ".Observable.g.cs"
            : model.Namespace + "." + model.ClassName + ".Observable.g.cs";

        ctx.AddSource(hintName, sb.ToString());
    }

    private static void EmitProperty(StringBuilder sb, ObservablePropertyModel prop)
    {
        if (!string.IsNullOrWhiteSpace(prop.XmlDoc))
            sb.AppendLine("    /// <inheritdoc/>");

        if (prop.NotifyOnTaskCompletion)
        {
            EmitTaskNotifierProperty(sb, prop);
            return;
        }

        // Explicit backing field. The partial property's implementation getter/setter
        // reference it directly. (C# 14 field keyword is for user-written partial props;
        // generator-emitted implementations use an explicit field for cross-version clarity.)
        sb.Append("    private ").Append(prop.TypeName).Append(' ').Append(prop.FieldName).AppendLine(";");
        sb.AppendLine();

        sb.Append("    public partial ").Append(prop.TypeName).Append(' ').AppendLine(prop.PropertyName);
        sb.AppendLine("    {");

        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.Append("        get => ").Append(prop.FieldName).AppendLine(";");

        if (!prop.IsReadOnly)
        {
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            EmitEqualityCheck(sb, prop);
            sb.Append("            On").Append(prop.PropertyName).Append("Changing(").Append(prop.FieldName).AppendLine(", value);");
            sb.Append("            NotifyChanging(in __desc_").Append(prop.PropertyName).AppendLine(");");
            sb.Append("            ").Append(prop.TypeName).Append(" __old = ").Append(prop.FieldName).AppendLine(";");
            sb.Append("            ").Append(prop.FieldName).AppendLine(" = value;");
            // Activation reassignment sync: if parent is active, deactivate old child, activate new
            if (prop.ParticipatesInActivation)
            {
                sb.AppendLine("            if (IsActive)");
                sb.AppendLine("            {");
                sb.Append("                __old").Append(prop.IsNullableActivatable ? "?" : "").AppendLine(".Deactivate();");
                sb.Append("                value").Append(prop.IsNullableActivatable ? "?" : "").AppendLine(".Activate();");
                sb.AppendLine("            }");
            }
            sb.Append("            On").Append(prop.PropertyName).AppendLine("Changed(__old, value);");
            sb.Append("            NotifyChanged(in __desc_").Append(prop.PropertyName).AppendLine(");");
            // Validation call (if any validators registered)
            if (!prop.ValidatorTypes.IsEmpty || !prop.AsyncValidatorTypes.IsEmpty)
                sb.Append("            Validate_").Append(prop.PropertyName).AppendLine("(value);");
            sb.AppendLine("        }");
        }

        // Close the property first, then emit partial hooks as class-level members below.
        sb.AppendLine("    }");

        if (!prop.IsReadOnly)
        {
            sb.Append("    partial void On").Append(prop.PropertyName)
              .Append("Changing(").Append(prop.TypeName).Append(" oldValue, ")
              .Append(prop.TypeName).AppendLine(" newValue);");
            sb.Append("    partial void On").Append(prop.PropertyName)
              .Append("Changed(").Append(prop.TypeName).Append(" oldValue, ")
              .Append(prop.TypeName).AppendLine(" newValue);");
        }
    }

    private static List<ObservablePropertyModel> FilterProperties(
        EquatableArray<ObservablePropertyModel> props,
        Func<ObservablePropertyModel, bool> predicate)
    {
        var result = new List<ObservablePropertyModel>();
        for (int i = 0; i < props.Length; i++)
            if (predicate(props[i])) result.Add(props[i]);
        return result;
    }

    private static void EmitValidationHelper(StringBuilder sb, ObservablePropertyModel prop)
    {
        // Sync validation helper: calls each IValidator<T>.Validate statically
        if (!prop.ValidatorTypes.IsEmpty)
        {
            sb.Append("    private void Validate_").Append(prop.PropertyName)
              .Append('(').Append(prop.TypeName).AppendLine(" value)");
            sb.AppendLine("    {");
            sb.AppendLine("        var __bag = Validation;");
            // Call each validator and aggregate errors; first error wins per property
            sb.AppendLine("        global::YFex.State.Validation.ValidationResult __vr = default;");
            foreach (var vt in prop.ValidatorTypes)
            {
                sb.Append("        __vr = ").Append(vt).AppendLine(".Validate(value);");
                sb.AppendLine("        if (!__vr.IsSuccess) { __bag.Set(__vr.Message!, __vr.Severity); return; }");
            }
            sb.Append("        __bag.Clear(\"").Append(prop.PropertyName).AppendLine("\");");
            sb.AppendLine("    }");
        }

        // Async validation helper: fire-and-forget
        if (!prop.AsyncValidatorTypes.IsEmpty)
        {
            sb.Append("    private async void Validate_").Append(prop.PropertyName)
              .Append("_Async(").Append(prop.TypeName).AppendLine(" value)");
            sb.AppendLine("    {");
            sb.AppendLine("        var __bag = Validation;");
            sb.AppendLine("        global::YFex.State.Validation.ValidationResult __vr = default;");
            foreach (var avt in prop.AsyncValidatorTypes)
            {
                sb.Append("        __vr = await ").Append(avt)
                  .AppendLine(".ValidateAsync(value, global::System.Threading.CancellationToken.None).ConfigureAwait(false);");
                sb.AppendLine("        if (!__vr.IsSuccess) { __bag.Set(__vr.Message!, __vr.Severity); return; }");
            }
            sb.Append("        __bag.Clear(\"").Append(prop.PropertyName).AppendLine("\");");
            sb.AppendLine("    }");
        }
    }

    private static void EmitTaskNotifierProperty(StringBuilder sb, ObservablePropertyModel prop)
    {
        // Backing field is TaskNotifier / TaskNotifier<T>; property type stays Task / Task<T>.
        // SetFieldAndNotifyOnCompletion does its own ReferenceEquals check, so no equality
        // strategy switch or partial hooks are emitted here.
        bool isGeneric = prop.TaskResultTypeFullName is not null;
        string notifierType = isGeneric
            ? $"global::YFex.State.TaskNotifier<{prop.TaskResultTypeFullName}>"
            : "global::YFex.State.TaskNotifier";

        sb.Append("    private ").Append(notifierType).Append("? ").Append(prop.FieldName).AppendLine(";");
        sb.AppendLine();

        sb.Append("    public partial ").Append(prop.TypeName).Append(' ').AppendLine(prop.PropertyName);
        sb.AppendLine("    {");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.Append("        get => ").Append(prop.FieldName).AppendLine(";");
        sb.Append("        set => SetFieldAndNotifyOnCompletion(ref ").Append(prop.FieldName)
          .Append(", value, in __desc_").Append(prop.PropertyName).AppendLine(");");
        sb.AppendLine("    }");
    }

    private static void EmitEqualityCheck(StringBuilder sb, ObservablePropertyModel prop)
    {
        string field = prop.FieldName;
        string type = prop.TypeName;

        sb.Append("            if (");

        switch (prop.EqualityKind)
        {
            case EqualityStrategy.DirectEquals:
                sb.Append(field).Append(" == value");
                break;

            case EqualityStrategy.FloatNaN:
                sb.Append(field).Append(" == value || (global::System.Single.IsNaN(").Append(field)
                  .Append(") && global::System.Single.IsNaN(value))");
                break;

            case EqualityStrategy.DoubleNaN:
                sb.Append(field).Append(" == value || (global::System.Double.IsNaN(").Append(field)
                  .Append(") && global::System.Double.IsNaN(value))");
                break;

            case EqualityStrategy.StringOrdinal:
                sb.Append("global::System.String.Equals(").Append(field)
                  .Append(", value, global::System.StringComparison.Ordinal)");
                break;

            case EqualityStrategy.ReferenceType:
                sb.Append("global::System.Object.ReferenceEquals(").Append(field)
                  .Append(", value) || (").Append(field).Append(" is not null && ")
                  .Append(field).Append(".Equals(value))");
                break;

            case EqualityStrategy.Custom when prop.CustomComparerType is not null:
                sb.Append(prop.CustomComparerType).Append(".Default.Equals(")
                  .Append(field).Append(", value)");
                break;

            default:
                sb.Append("global::System.Collections.Generic.EqualityComparer<")
                  .Append(type).Append(">.Default.Equals(").Append(field).Append(", value)");
                break;
        }

        sb.AppendLine(") return;");
    }
}
