<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Generator options -->
    <YFexXmlGeneratedNamespace>Sample.Generated</YFexXmlGeneratedNamespace>
    <YFexXmlEmitFacetStructs>true</YFexXmlEmitFacetStructs>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="YFexXmlGeneratedNamespace" />
    <CompilerVisibleProperty Include="YFexXmlEmitFacetStructs" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="sample.xsd" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YFex.Xml\YFex.Xml.csproj" />
    <ProjectReference Include="..\YFex.Xml.SourceGenerator\YFex.Xml.SourceGenerator.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
