<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0-windows</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\YFex.Security\YFex.Security.csproj" />
    <ProjectReference Include="..\YFex.Windows.Security\YFex.Windows.Security.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.*" />
    <PackageReference Include="SharpPcap" Version="6.*" />
    <PackageReference Include="PacketDotNet" Version="1.*" />
  </ItemGroup>

</Project>
