using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace YFex.Persistence.Generator;

internal static class PersistenceEmitter
{
    public static void Emit(SourceProductionContext spc, PersistenceClassModel model)
    {
        // Report YFPER0001 for properties whose type might not be MemoryPack-serializable
        foreach (var prop in model.Properties.Items)
        {
            if (!prop.IsKnownSerializable)
                spc.ReportDiagnostic(Diagnostic.Create(
                    PersistenceDiagnostics.YFPER0001,
                    Location.None,
                    prop.Name,
                    prop.TypeFqn));
        }

        string source   = GenerateSource(model);
        string fileName = $"{model.ClassName}.Persistence.g.cs";
        spc.AddSource(fileName, source);
    }

    private static string GenerateSource(PersistenceClassModel model)
    {
        var sb = new StringBuilder(2048);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.Append("namespace "); sb.Append(model.Namespace); sb.AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("partial class "); sb.Append(model.ClassName);
        sb.AppendLine(" : global::YFex.Persistence.IPersistableStateObject");
        sb.AppendLine("{");

        AppendCaptureSnapshot(sb, model);
        sb.AppendLine();
        AppendRestoreSnapshot(sb, model);

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ── CaptureSnapshot ───────────────────────────────────────────────────────

    private static void AppendCaptureSnapshot(StringBuilder sb, PersistenceClassModel model)
    {
        sb.AppendLine("    public virtual byte[] CaptureSnapshot()");
        sb.AppendLine("    {");
        sb.AppendLine("        // Each property is serialized individually to a byte[],");
        sb.AppendLine("        // then the array of byte[] is wrapped with MemoryPack.");
        sb.Append("        byte[][] __values = new byte[][]");
        sb.AppendLine();
        sb.AppendLine("        {");

        foreach (var prop in model.Properties.Items)
        {
            sb.Append("            global::MemoryPack.MemoryPackSerializer.Serialize<");
            sb.Append(prop.TypeFqn);
            sb.Append(">(");
            sb.Append(prop.Name);
            sb.AppendLine("),");
        }

        sb.AppendLine("        };");
        sb.AppendLine("        return global::MemoryPack.MemoryPackSerializer.Serialize(__values);");
        sb.AppendLine("    }");
    }

    // ── RestoreSnapshot ───────────────────────────────────────────────────────

    private static void AppendRestoreSnapshot(StringBuilder sb, PersistenceClassModel model)
    {
        sb.AppendLine("    public virtual void RestoreSnapshot(global::System.ReadOnlySpan<byte> data)");
        sb.AppendLine("    {");
        sb.AppendLine("        var __values = global::MemoryPack.MemoryPackSerializer.Deserialize<byte[][]>(data);");
        sb.AppendLine("        if (__values is null) return;");
        sb.AppendLine();

        var props = model.Properties.Items;
        for (int i = 0; i < props.Length; i++)
        {
            var prop = props[i];
            sb.Append("        if (__values.Length > "); sb.Append(i); sb.AppendLine(")");
            sb.Append("            ");
            sb.Append(prop.Name);
            sb.Append(" = global::MemoryPack.MemoryPackSerializer.Deserialize<");
            sb.Append(prop.TypeFqn);
            sb.Append(">(__values["); sb.Append(i); sb.AppendLine("])");

            // For non-nullable value types, fall back to default
            if (prop.TypeFqn.EndsWith("?") == false)
            {
                // Might be nullable at MemoryPack level even if not in C#;
                // the `!` avoids a nullable warning without extra logic
                sb.Remove(sb.Length - 1, 1); // remove newline
                sb.AppendLine("!;");
            }
            else
            {
                sb.Remove(sb.Length - 1, 1);
                sb.AppendLine(";");
            }
        }

        sb.AppendLine("    }");
    }
}
