//using Microsoft.CodeAnalysis;
//using Xunit;

//namespace YFex.NavigatR.Generator.Tests;

//public sealed class RouteGenerationTests
//{
//    private const string Usings = """
//        using System.Threading;
//        using System.Threading.Tasks;
//        using YFex.NavigatR;
//        """;

//    // ─────────────────────────────────────────────────────────────────────────
//    // Route class name derivation
//    // ─────────────────────────────────────────────────────────────────────────

//    [Theory]
//    [InlineData("order", "OrderRoute")]
//    [InlineData("userProfile", "UserProfileRoute")]
//    [InlineData("edit-user", "EditUserRoute")]
//    [InlineData("edit_invoice", "EditInvoiceRoute")]
//    [InlineData("a", "ARoute")]
//    [InlineData("ABC", "ABCRoute")]
//    public void DeriveRouteClassName_VariousInputs_ProducesExpectedName(string input, string expected)
//        => Assert.Equal(expected, GeneratorTestHelper.DeriveRouteClassName(input));

//    // ─────────────────────────────────────────────────────────────────────────
//    // Auto-generate — simple INavigable (no parameter, no result)
//    // ─────────────────────────────────────────────────────────────────────────

//    [Fact]
//    public void AutoGenerate_SimpleNavigable_GeneratesIRouteRecord()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            [Route("home")]
//            public partial class HomeViewModel : INavigable
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//            }
//            """;

//        var output = GeneratorTestHelper.GetSourceByHint(source, "HomeRoute.g.cs");

//        Assert.Contains("// <auto-generated/>", output);
//        Assert.Contains("#nullable enable", output);
//        Assert.Contains("namespace MyApp;", output);
//        Assert.Contains("public sealed record HomeRoute", output);
//        Assert.Contains(": global::YFex.NavigatR.IRoute", output);
//        Assert.Contains("public string? DisplayName => null;", output);
//        // No constructor parameter when no param declared
//        Assert.DoesNotContain("Params", output);
//    }

//    [Fact]
//    public void AutoGenerate_WithDisplayName_IncludesDisplayNameInRoute()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            [Route("home", DisplayName = "Dashboard")]
//            public partial class HomeViewModel : INavigable
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//            }
//            """;

//        var output = GeneratorTestHelper.GetSourceByHint(source, "HomeRoute.g.cs");

//        Assert.Contains("public string? DisplayName => \"Dashboard\";", output);
//    }

//    // ─────────────────────────────────────────────────────────────────────────
//    // Auto-generate — with required parameter
//    // Route gets constructor parameter, ViewModel gets bridge + typed partial
//    // ─────────────────────────────────────────────────────────────────────────

//    [Fact]
//    public void AutoGenerate_WithRequiredParameter_GeneratesRouteWithConstructor()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            public sealed record OrderParams(int OrderId);

//            [Route("order", Parameter = typeof(OrderParams))]
//            public partial class OrderViewModel : INavigable
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//            }
//            """;

//        var output = GeneratorTestHelper.GetSourceByHint(source, "OrderRoute.g.cs");

//        // Route has constructor with required param
//        Assert.Contains("public sealed record OrderRoute(global::MyApp.OrderParams Params)", output);
//        Assert.Contains(": global::YFex.NavigatR.IRoute", output);
//        Assert.DoesNotContain("IRouteAccepts", output); // removed
//    }

//    [Fact]
//    public void AutoGenerate_WithOptionalParameter_GeneratesNullableConstructor()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            public sealed record SearchParams(string Query);

//            [Route("search", Parameter = typeof(SearchParams), ParameterRequired = false)]
//            public partial class SearchViewModel : INavigable
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//            }
//            """;

//        var output = GeneratorTestHelper.GetSourceByHint(source, "SearchRoute.g.cs");

//        // Optional — nullable with default null
//        Assert.Contains("global::MyApp.SearchParams? Params = null", output);
//    }

//    // ─────────────────────────────────────────────────────────────────────────
//    // Auto-generate — with INavigable<TResult>
//    // ─────────────────────────────────────────────────────────────────────────

//    [Fact]
//    public void AutoGenerate_WithResult_GeneratesIRouteProduces()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            public sealed record PickerResult(string Item);

//            [Route("picker")]
//            public partial class PickerViewModel : INavigable<PickerResult>
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//                public Task<global::YFex.NavigatR.NavigationResult<PickerResult>> WaitForResultAsync() => throw new System.NotImplementedException();
//            }
//            """;

//        var output = GeneratorTestHelper.GetSourceByHint(source, "PickerRoute.g.cs");

//        Assert.Contains("IRouteProduces<global::MyApp.PickerResult>", output);
//        Assert.DoesNotContain("Params", output); // no constructor when no param
//    }

//    // ─────────────────────────────────────────────────────────────────────────
//    // ViewModel partial — parameter bridge uses direct cast, no reflection
//    // ─────────────────────────────────────────────────────────────────────────

//    [Fact]
//    public void ViewModelPartial_WithRequiredParameter_GeneratesDirectCastBridge()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            public sealed record OrderParams(int OrderId);

//            [Route("order", Parameter = typeof(OrderParams))]
//            public partial class OrderViewModel : INavigable
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//            }
//            """;

//        var output = GeneratorTestHelper.GetSourceByHint(source, "OrderViewModel.NavigatR.g.cs");

//        // Explicit interface bridge with direct cast — no GetParameter<T>()
//        Assert.Contains("global::YFex.NavigatR.INavigable.OnNavigation(", output);
//        Assert.Contains("((global::MyApp.OrderRoute)context.Route).Params", output);
//        Assert.DoesNotContain("GetParameter<", output);
//        Assert.DoesNotContain("TryGetParameter<", output);

//        // Enforced partial
//        Assert.Contains("public partial global::System.Threading.Tasks.Task OnNavigation(", output);
//        Assert.Contains("global::MyApp.OrderParams parameter,", output);
//    }

//    [Fact]
//    public void ViewModelPartial_WithOptionalParameter_GeneratesNullablePartialAndDirectCast()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            public sealed record SearchParams(string Query);

//            [Route("search", Parameter = typeof(SearchParams), ParameterRequired = false)]
//            public partial class SearchViewModel : INavigable
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//            }
//            """;

//        var output = GeneratorTestHelper.GetSourceByHint(source, "SearchViewModel.NavigatR.g.cs");

//        // Nullable parameter type
//        Assert.Contains("global::MyApp.SearchParams? parameter,", output);
//        // Direct cast for optional too
//        Assert.Contains("((global::MyApp.SearchRoute)context.Route).Params", output);
//    }

//    [Fact]
//    public void ViewModelPartial_FileScopedExtension_UsesDirectCast()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            public sealed record OrderParams(int OrderId);

//            [Route("order", Parameter = typeof(OrderParams))]
//            public partial class OrderViewModel : INavigable
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//            }
//            """;

//        var output = GeneratorTestHelper.GetSourceByHint(source, "OrderViewModel.NavigatR.g.cs");

//        // File-scoped extension uses direct cast
//        Assert.Contains("file static class NavigationContextExtensions_OrderViewModel", output);
//        Assert.Contains("((global::MyApp.OrderRoute)context.Route).Params", output);
//        Assert.DoesNotContain("context.GetParameter<", output);
//    }

//    // ─────────────────────────────────────────────────────────────────────────
//    // ViewModel partial — result (Returns/Cancel/Deny/WaitForResultAsync)
//    // ─────────────────────────────────────────────────────────────────────────

//    [Fact]
//    public void ViewModelPartial_WithResult_GeneratesReturnsCancelDenyAndWaitForResult()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            public sealed record PickerResult(string Item);

//            [Route("picker")]
//            public partial class PickerViewModel : INavigable<PickerResult>
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//                public Task<global::YFex.NavigatR.NavigationResult<PickerResult>> WaitForResultAsync() => throw new System.NotImplementedException();
//            }
//            """;

//        var output = GeneratorTestHelper.GetSourceByHint(source, "PickerViewModel.NavigatR.g.cs");

//        Assert.Contains("_navigationResultTcs", output);
//        Assert.Contains("public void Returns(global::MyApp.PickerResult result)", output);
//        Assert.Contains("public void Cancel()", output);
//        Assert.Contains("public void Deny(string? reason = null)", output);
//        Assert.Contains("INavigable<global::MyApp.PickerResult>.WaitForResultAsync()", output);
//        Assert.Contains("NavigationResult<global::MyApp.PickerResult>.Success(result)", output);
//    }

//    // ─────────────────────────────────────────────────────────────────────────
//    // Registration file
//    // ─────────────────────────────────────────────────────────────────────────

//    [Fact]
//    public void Registration_SingleViewModel_GeneratesRegisterCall()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            [Route("home")]
//            public partial class HomeViewModel : INavigable
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//            }
//            """;

//        var output = GeneratorTestHelper.GetSourceByHint(source, "NavigatRRegistration.g.cs");

//        Assert.Contains("static partial void RegisterGenerated", output);
//        Assert.Contains("registry.Register<global::MyApp.HomeRoute, global::MyApp.HomeViewModel>()", output);
//    }

//    [Fact]
//    public void Registration_MultipleViewModels_GeneratesAllRegisterCalls()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            [Route("home")]
//            public partial class HomeViewModel : INavigable
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//            }

//            public sealed record OrderParams(int Id);

//            [Route("order", Parameter = typeof(OrderParams))]
//            public partial class OrderViewModel : INavigable
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//            }
//            """;

//        var output = GeneratorTestHelper.GetSourceByHint(source, "NavigatRRegistration.g.cs");

//        Assert.Contains("global::MyApp.HomeRoute, global::MyApp.HomeViewModel", output);
//        Assert.Contains("global::MyApp.OrderRoute, global::MyApp.OrderViewModel", output);
//    }

//    // ─────────────────────────────────────────────────────────────────────────
//    // Diagnostics
//    // ─────────────────────────────────────────────────────────────────────────

//    [Fact]
//    public void NAV001_NonPartialClass_EmitsDiagnostic()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            [Route("home")]
//            public class HomeViewModel : INavigable
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//            }
//            """;

//        var diagnostics = GeneratorTestHelper.GetDiagnostics(source);

//        Assert.Contains(diagnostics, d => d.Id == "NAV001");
//    }

//    [Fact]
//    public void NAV002_DoesNotImplementINavigable_EmitsDiagnostic()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            [Route("home")]
//            public partial class HomeViewModel
//            {
//            }
//            """;

//        var diagnostics = GeneratorTestHelper.GetDiagnostics(source);

//        Assert.Contains(diagnostics, d => d.Id == "NAV002");
//    }

//    [Fact]
//    public void NAV003_ManualRouteTypeNotIRoute_EmitsDiagnostic()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            public sealed class NotARoute { }

//            [Route(typeof(NotARoute))]
//            public partial class HomeViewModel : INavigable
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//            }
//            """;

//        var diagnostics = GeneratorTestHelper.GetDiagnostics(source);

//        Assert.Contains(diagnostics, d => d.Id == "NAV003");
//    }

//    // ─────────────────────────────────────────────────────────────────────────
//    // Generated code quality
//    // ─────────────────────────────────────────────────────────────────────────

//    [Fact]
//    public void AllGeneratedFiles_HaveAutoGeneratedHeader()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            [Route("home")]
//            public partial class HomeViewModel : INavigable
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//            }
//            """;

//        var sources = GeneratorTestHelper.GetGeneratedSources(source);

//        foreach (var s in sources)
//        {
//            Assert.StartsWith("// <auto-generated/>", s.TrimStart());
//            Assert.Contains("#nullable enable", s);
//        }
//    }

//    [Fact]
//    public void AllGeneratedFiles_UseGlobalQualifiedNames()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            public sealed record PickerResult(string Item);

//            [Route("picker")]
//            public partial class PickerViewModel : INavigable<PickerResult>
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//                public Task<global::YFex.NavigatR.NavigationResult<PickerResult>> WaitForResultAsync() => throw new System.NotImplementedException();
//            }
//            """;

//        var sources = GeneratorTestHelper.GetGeneratedSources(source);

//        foreach (var s in sources)
//            Assert.DoesNotContain("using YFex", s);
//    }

//    [Fact]
//    public void GeneratedRouteWithParameter_HasNoSyntaxErrors()
//    {
//        const string source = Usings + """
//            namespace MyApp;

//            public sealed record OrderParams(int Id);
//            public sealed record OrderResult(string Ref);

//            [Route("order", Parameter = typeof(OrderParams))]
//            public partial class OrderViewModel : INavigable<OrderResult>
//            {
//                public Task OnNavigation(NavigationContext ctx, CancellationToken ct) => Task.CompletedTask;
//                public Task OnResume(CancellationToken ct) => Task.CompletedTask;
//                public Task OnSuspend(CancellationToken ct) => Task.CompletedTask;
//                public void Dispose() { }
//                public Task<global::YFex.NavigatR.NavigationResult<OrderResult>> WaitForResultAsync() => throw new System.NotImplementedException();
//            }
//            """;

//        var result = GeneratorTestHelper.Run(source);

//        foreach (var tree in result.GeneratedTrees)
//        {
//            var errors = tree.GetDiagnostics()
//                .Where(d => d.Severity == DiagnosticSeverity.Error)
//                .ToList();
//            Assert.Empty(errors);
//        }
//    }
//}